{
  "hash": "8e68011f04b868fb535360653316c9f1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Your Name Here\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(sf)\nlibrary(tidyverse)\nlibrary(tigris)\nlibrary(tidycensus)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(here)\nlibrary(knitr)\n\n# Load spatial data\npa_counties <- st_read(here(\"C:/Users/wensh/Desktop/MUSA5080/week-04/data/Pennsylvania_County_Boundaries.shp\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `C:\\Users\\wensh\\Desktop\\MUSA5080\\week-04\\data\\Pennsylvania_County_Boundaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals <- st_read(here(\"C:/Users/wensh/Desktop/MUSA5080/week-04/data/hospitals.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `C:\\Users\\wensh\\Desktop\\MUSA5080\\week-04\\data\\hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ncensus_tracts <- tracts(state = \"PA\", cb = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=                                                                     |   2%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |===                                                                   |   5%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |=====                                                                 |   8%\n  |                                                                            \n  |======                                                                |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |=======                                                               |  11%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |========                                                              |  12%\n  |                                                                            \n  |=========                                                             |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |==========                                                            |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |============                                                          |  18%\n  |                                                                            \n  |=============                                                         |  18%\n  |                                                                            \n  |==============                                                        |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |================                                                      |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |==================                                                    |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |=======================                                               |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |=========================                                             |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |===========================                                           |  38%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |===============================                                       |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |=================================                                     |  48%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |====================================                                  |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |======================================                                |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |========================================                              |  58%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |==========================================                            |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |============================================                          |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |==============================================                        |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |================================================                      |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |==================================================                    |  71%\n  |                                                                            \n  |===================================================                   |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |=====================================================                 |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |=======================================================               |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |=========================================================             |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |===========================================================           |  85%\n  |                                                                            \n  |============================================================          |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |================================================================      |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |==================================================================    |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |====================================================================  |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check that all data loaded correctly\nhead(pa_counties)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8905670 ymin: 4862594 xmax: -8317930 ymax: 5161279\nProjected CRS: WGS 84 / Pseudo-Mercator\n  OBJECTID MSLINK COUNTY_NAM COUNTY_NUM FIPS_COUNT COUNTY_ARE COUNTY_PER\n1      336     46 MONTGOMERY         46        091       <NA>       <NA>\n2      337      8   BRADFORD         08        015       <NA>       <NA>\n3      338      9      BUCKS         09        017       <NA>       <NA>\n4      339     58      TIOGA         58        117       <NA>       <NA>\n5      340     59      UNION         59        119       <NA>       <NA>\n6      341     60    VENANGO         60        121       <NA>       <NA>\n  NUMERIC_LA COUNTY_N_1 AREA_SQ_MI SOUND SPREAD_SHE IMAGE_NAME NOTE_FILE VIDEO\n1          5         46   487.4271  <NA>       <NA>   poll.bmp      <NA>  <NA>\n2          2          8  1161.3379  <NA>       <NA>   poll.bmp      <NA>  <NA>\n3          5          9   622.0836  <NA>       <NA>   poll.bmp      <NA>  <NA>\n4          2         58  1137.2480  <NA>       <NA>   poll.bmp      <NA>  <NA>\n5          2         59   319.1893  <NA>       <NA>   poll.bmp      <NA>  <NA>\n6          3         60   683.3676  <NA>       <NA>   poll.bmp      <NA>  <NA>\n  DISTRICT_N PA_CTY_COD MAINT_CTY_ DISTRICT_O                       geometry\n1         06         46          4        6-4 MULTIPOLYGON (((-8398884 48...\n2         03         08          9        3-9 MULTIPOLYGON (((-8558633 51...\n3         06         09          1        6-1 MULTIPOLYGON (((-8367360 49...\n4         03         59          7        3-7 MULTIPOLYGON (((-8558633 51...\n5         03         60          8        3-8 MULTIPOLYGON (((-8562865 49...\n6         01         61          5        1-5 MULTIPOLYGON (((-8870781 50...\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(hospitals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.27907 ymin: 39.80913 xmax: -75.17005 ymax: 40.24273\nGeodetic CRS:  WGS 84\n                 CHIEF_EXEC              CHIEF_EX_1\n1             Peter J Adamo               President\n2          Autumn DeShields Chief Executive Officer\n3              Shawn Parekh Chief Executive Officer\n4               DIANE HRITZ Chief Executive Officer\n5            Tim Harclerode Chief Executive Officer\n6 Richard McLaughlin MD MBA Chief Executive Officer\n                      FACILITY_U LONGITUDE       COUNTY\n1   https://www.phhealthcare.org -79.91131   Washington\n2      https://www.malvernbh.com -75.17005 Philadelphia\n3 https://roxboroughmemorial.com -75.20963 Philadelphia\n4     https://www.ashospital.net -80.27907   Washington\n5      https://www.conemaugh.org -79.02513     Somerset\n6        https://towerhealth.org -75.61213   Montgomery\n                               FACILITY_N                         STREET\n1               Penn Highlands Mon Valley         1163 Country Club Road\n2               MALVERN BEHAVIORAL HEALTH 1930 South Broad Street Unit 4\n3            Roxborough Memorial Hospital              5800 Ridge Avenue\n4              ADVANCED SURGICAL HOSPITAL       100 TRICH DRIVE\\nSUITE 1\n5 DLP Conemaugh Meyersdale Medical Center             200 Hospital Drive\n6                 Pottstown Hospital, LLC          1600 East High Street\n    CITY_OR_BO LATITUDE   TELEPHONE_ ZIP_CODE                   geometry\n1  Monongahela 40.18193 724-258-1000    15063 POINT (-79.91131 40.18193)\n2 Philadelphia 39.92619 610-480-8919    19145  POINT (-75.17005 39.9262)\n3 Philadelphia 40.02869 215-483-9900    19128 POINT (-75.20963 40.02869)\n4   WASHINGTON 40.15655   7248840710    15301 POINT (-80.27907 40.15655)\n5   Meyersdale 39.80913 814-634-5911    15552 POINT (-79.02513 39.80913)\n6    Pottstown 40.24273   6103277000    19464 POINT (-75.61213 40.24273)\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(census_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 13 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -78.42478 ymin: 39.79351 xmax: -75.93766 ymax: 40.54328\nGeodetic CRS:  NAD83\n  STATEFP COUNTYFP TRACTCE              GEOIDFQ       GEOID   NAME\n1      42      001  031101 1400000US42001031101 42001031101 311.01\n2      42      013  100400 1400000US42013100400 42013100400   1004\n3      42      013  100500 1400000US42013100500 42013100500   1005\n4      42      013  100800 1400000US42013100800 42013100800   1008\n5      42      013  101900 1400000US42013101900 42013101900   1019\n6      42      011  011200 1400000US42011011200 42011011200    112\n             NAMELSAD STUSPS   NAMELSADCO   STATE_NAME LSAD   ALAND AWATER\n1 Census Tract 311.01     PA Adams County Pennsylvania   CT 3043185      0\n2   Census Tract 1004     PA Blair County Pennsylvania   CT  993724      0\n3   Census Tract 1005     PA Blair County Pennsylvania   CT 1130204      0\n4   Census Tract 1008     PA Blair County Pennsylvania   CT  996553      0\n5   Census Tract 1019     PA Blair County Pennsylvania   CT  573726      0\n6    Census Tract 112     PA Berks County Pennsylvania   CT 1539365   9308\n                        geometry\n1 MULTIPOLYGON (((-77.03108 3...\n2 MULTIPOLYGON (((-78.42478 4...\n3 MULTIPOLYGON (((-78.41661 4...\n4 MULTIPOLYGON (((-78.41067 4...\n5 MULTIPOLYGON (((-78.40836 4...\n6 MULTIPOLYGON (((-75.95433 4...\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset?\n\n  233\n\n- How many census tracts?\n\n  3445\n\n- What coordinate reference system is each dataset in?\n\n  census tract and metro areas are in NAD83, while the rest three are in WGS84\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\ndf=load_variables(2023,\"acs5/profile\")\ndata=c(population=\"DP02_0018\",age=\"DP05_0024\",income=\"DP03_0062\")\ndf = get_acs(state = \"PA\",\n              variables = data,\n              survey = \"acs5\",\n             geometry = TRUE,\n             geography = \"tract\",\n             output = \"wide\",\n             year = 2023)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\n# Join to tract boundaries\n#I already downloaded my geography when using tidycensus\nsum(is.na(df$incomeE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 66\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(df$incomeE,na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 72943.5\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using?\n\n  2019-2023 5 year acs\n\n- How many tracts have missing income data?\n\n  66\n\n- What is the median income across all PA census tracts?\n\n  72943.5\n  \n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\n\nsummary(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    GEOID               NAME            populationE     populationM    \n Length:3446        Length:3446        Min.   :    0   Min.   :   7.0  \n Class :character   Class :character   1st Qu.: 2506   1st Qu.: 246.2  \n Mode  :character   Mode  :character   Median : 3522   Median : 375.0  \n                                       Mean   : 3646   Mean   : 402.4  \n                                       3rd Qu.: 4658   3rd Qu.: 527.0  \n                                       Max.   :10388   Max.   :2092.0  \n                                                                       \n      ageE             ageM          incomeE          incomeM      \n Min.   :   0.0   Min.   :  3.0   Min.   : 13307   Min.   :   472  \n 1st Qu.: 429.0   1st Qu.: 94.0   1st Qu.: 57864   1st Qu.:  9324  \n Median : 665.0   Median :138.0   Median : 72944   Median : 13780  \n Mean   : 718.6   Mean   :156.2   Mean   : 80731   Mean   : 16219  \n 3rd Qu.: 945.0   3rd Qu.:199.0   3rd Qu.: 96691   3rd Qu.: 20141  \n Max.   :2541.0   Max.   :826.0   Max.   :250001   Max.   :208341  \n                                  NA's   :66       NA's   :74      \n          geometry   \n MULTIPOLYGON :3446  \n epsg:4269    :   0  \n +proj=long...:   0  \n                     \n                     \n                     \n                     \n```\n\n\n:::\n\n```{.r .cell-code}\nvulnerable=df%>%\n  filter(ageE>945|incomeE<32150)\n\nprint(vulnerable)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 974 features and 8 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -80.51989 ymin: 39.7198 xmax: -74.77683 ymax: 42.18103\nGeodetic CRS:  NAD83\nFirst 10 features:\n         GEOID                                             NAME populationE\n1  42001031101  Census Tract 311.01; Adams County; Pennsylvania        4865\n2  42011000100       Census Tract 1; Berks County; Pennsylvania        4357\n3  42011013302  Census Tract 133.02; Berks County; Pennsylvania        6438\n4  42015950300 Census Tract 9503; Bradford County; Pennsylvania        5389\n5  42017101607 Census Tract 1016.07; Bucks County; Pennsylvania        4564\n6  42017101403 Census Tract 1014.03; Bucks County; Pennsylvania        6207\n7  42017104901 Census Tract 1049.01; Bucks County; Pennsylvania        6762\n8  42025020700    Census Tract 207; Carbon County; Pennsylvania        5256\n9  42027011800    Census Tract 118; Centre County; Pennsylvania        5904\n10 42029304000  Census Tract 3040; Chester County; Pennsylvania        5363\n   populationM ageE ageM incomeE incomeM                       geometry\n1          412  995  261   64985   10752 MULTIPOLYGON (((-77.03108 3...\n2          642  684  235   24613    6851 MULTIPOLYGON (((-75.93179 4...\n3          279 2017  414   96063    8531 MULTIPOLYGON (((-75.65603 4...\n4           20 1056  186   55393   15400 MULTIPOLYGON (((-76.53679 4...\n5          604 1602  430   93580   26482 MULTIPOLYGON (((-75.08177 4...\n6          593 1365  311  105927   36551 MULTIPOLYGON (((-74.98383 4...\n7          747 1067  172  173708    6918 MULTIPOLYGON (((-75.11312 4...\n8          225  951  223   81875   11766 MULTIPOLYGON (((-75.71378 4...\n9           19 1178  223  107769   16251 MULTIPOLYGON (((-77.83571 4...\n10          25  952  204   97772    7400 MULTIPOLYGON (((-75.70888 3...\n```\n\n\n:::\n\n```{.r .cell-code}\n974/3446\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2826465\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n\n- What income threshold did you choose and why?\n\n  I chose $32,150, which is the penn poverty line \n\n- What elderly population threshold did you choose and why?\n\n  I chose the 3rd quantile \n\n- How many tracts meet your vulnerability criteria?\n\n  974\n\n- What percentage of PA census tracts are considered vulnerable by your definition?\n\n  28%\n\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\nvulnerable_proj=vulnerable%>%\n  st_transform(3365)\n\nhost_proj=hospitals%>%\n  st_transform(3365)\n\n# Calculate distance from each tract centroid to nearest hospital\nvulnerable_center=st_centroid(vulnerable_proj)\n\ndist <- vulnerable_center %>%\n  mutate(\n    dis_to_tract = apply(\n      st_distance(st_centroid(vulnerable_center), host_proj),\n      1,\n      min\n    ) *0.000189\n  )\n\nmean(dist$dis_to_tract)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.173085\n```\n\n\n:::\n\n```{.r .cell-code}\nmax(dist$dis_to_tract)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25.90749\n```\n\n\n:::\n\n```{.r .cell-code}\ndist$indi=ifelse(dist$dis_to_tract>15,1,0)\nsummary(dist$indi==1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Mode   FALSE    TRUE \nlogical     957      17 \n```\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts?\n  \n  4.17\n\n- What is the maximum distance?\n  \n  25.91\n\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\n  \n  17\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\nunderserved=dist%>%\n  filter(indi==1)\n17/973\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01747174\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved?\n  \n  17\n\n- What percentage of vulnerable tracts are underserved?\n  \n  1.7%\n\n- Does this surprise you? Why or why not?\n  \n  Yes, as 15 miles is such a long way and there are still 17 tracts that are so far away, it should be less than 10\n  \n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\ndf = get_acs(state = \"PA\",\n              variables = data,\n              survey = \"acs5\",\n             geometry = TRUE,\n             geography = \"county\",\n             output = \"wide\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |                                                                      |   1%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |=                                                                     |   2%\n  |                                                                            \n  |==                                                                    |   2%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |==                                                                    |   4%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |===                                                                   |   5%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |=====                                                                 |   8%\n  |                                                                            \n  |======                                                                |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |=======                                                               |  11%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |========                                                              |  12%\n  |                                                                            \n  |=========                                                             |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |=========                                                             |  14%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |==========                                                            |  15%\n  |                                                                            \n  |===========                                                           |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |============                                                          |  18%\n  |                                                                            \n  |=============                                                         |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |==============                                                        |  21%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |================                                                      |  24%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |=================                                                     |  25%\n  |                                                                            \n  |==================                                                    |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |===================                                                   |  28%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |=====================                                                 |  31%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |======================                                                |  32%\n  |                                                                            \n  |=======================                                               |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |=======================                                               |  34%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |========================                                              |  35%\n  |                                                                            \n  |=========================                                             |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |==========================                                            |  38%\n  |                                                                            \n  |===========================                                           |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |============================                                          |  41%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |=============================                                         |  42%\n  |                                                                            \n  |==============================                                        |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |===============================                                       |  45%\n  |                                                                            \n  |================================                                      |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |=================================                                     |  48%\n  |                                                                            \n  |==================================                                    |  48%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |===================================                                   |  51%\n  |                                                                            \n  |====================================                                  |  51%\n  |                                                                            \n  |====================================                                  |  52%\n  |                                                                            \n  |=====================================                                 |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |======================================                                |  55%\n  |                                                                            \n  |=======================================                               |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |========================================                              |  58%\n  |                                                                            \n  |=========================================                             |  58%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |==========================================                            |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |==========================================                            |  61%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |===========================================                           |  62%\n  |                                                                            \n  |============================================                          |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |=============================================                         |  65%\n  |                                                                            \n  |==============================================                        |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |===============================================                       |  68%\n  |                                                                            \n  |================================================                      |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |=================================================                     |  71%\n  |                                                                            \n  |==================================================                    |  71%\n  |                                                                            \n  |==================================================                    |  72%\n  |                                                                            \n  |===================================================                   |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |====================================================                  |  75%\n  |                                                                            \n  |=====================================================                 |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |======================================================                |  78%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |=======================================================               |  79%\n  |                                                                            \n  |========================================================              |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |========================================================              |  81%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |=========================================================             |  82%\n  |                                                                            \n  |==========================================================            |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |==========================================================            |  84%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |===========================================================           |  85%\n  |                                                                            \n  |============================================================          |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |=============================================================         |  88%\n  |                                                                            \n  |==============================================================        |  88%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |===============================================================       |  91%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |================================================================      |  92%\n  |                                                                            \n  |=================================================================     |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |=================================================================     |  94%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |==================================================================    |  95%\n  |                                                                            \n  |===================================================================   |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |====================================================================  |  98%\n  |                                                                            \n  |===================================================================== |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================|  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\n# Aggregate statistics by county\n\ndist_final=dist%>%\n  st_drop_geometry()%>%\n  mutate(NAME=str_remove(NAME,\"; Pennsylvania\"))\n\ndist_final[,11:12] = str_split_fixed(dist_final$NAME,\";\",2)\n\ndf_removed=df%>%\n  mutate(NAME=str_remove(NAME,\", Pennsylvania\"))%>%\n  mutate(NAME = str_trim(str_to_title(NAME)))\n         \ndist_final2=dist_final%>%\n  mutate(NAME=V12)%>%\n  mutate(NAME = str_trim(str_to_title(NAME)))%>%\n  group_by(NAME)%>%\n  summarise(\n    vulnerable=n(),\n    underserved=sum(indi==1),\n    per=underserved/vulnerable,\n    avg_dis=mean(dis_to_tract),\n    vulner_pop=sum(populationE)\n  )\n\ndf_removed=df_removed%>%\n  left_join(dist_final2,by=\"NAME\")\n```\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\n\n  Pike, Wyoming, Bradford, Clearfield, and Snyder\n\n- Which counties have the most vulnerable people living far from hospitals?\n\n  Allegheny County\n\n- Are there any patterns in where underserved counties are located?\n\n  They are all far from the major cities, which tends to have better medical care services\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(scales)\n# Create and format priority counties table\ndf_table=df_removed%>%\n  st_drop_geometry()%>%\n  mutate(percentage=round(per*100,digits = 3))%>%\n  mutate(pop=comma(populationE))%>%\n  mutate(distance=round(avg_dis,digits = 3))%>%\n  select(NAME,pop,vulnerable,underserved, percentage, distance, vulner_pop)\n \nfinal_table=df_table[order(df_table$percentage,decreasing=TRUE),]\n\n\n\n\nkable(final_table, col.names=c(\"County Name\",\"Population\",\"Number of Vulnerable Tracts\",\"Underserved Tracts\",\n                            \"Percentage of Underserved Tract\",\"Average Distance to Nearest Hospital\",\n                            \"Vulnerable Population\"),format = \"html\",row.names = FALSE,\n      bootstrap_options=c(\"striped\", \"hover\", \"condensed\"),\n    full_width = FALSE,\n    position = \"center\",caption = \"County-level summary of population, vulnerable tracts, underserved tracts, and hospital accessibility in Pennsylvania.\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table>\n<caption>County-level summary of population, vulnerable tracts, underserved tracts, and hospital accessibility in Pennsylvania.</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> County Name </th>\n   <th style=\"text-align:left;\"> Population </th>\n   <th style=\"text-align:right;\"> Number of Vulnerable Tracts </th>\n   <th style=\"text-align:right;\"> Underserved Tracts </th>\n   <th style=\"text-align:right;\"> Percentage of Underserved Tract </th>\n   <th style=\"text-align:right;\"> Average Distance to Nearest Hospital </th>\n   <th style=\"text-align:right;\"> Vulnerable Population </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Pike County </td>\n   <td style=\"text-align:left;\"> 59,299 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 100.000 </td>\n   <td style=\"text-align:right;\"> 23.530 </td>\n   <td style=\"text-align:right;\"> 8286 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Wyoming County </td>\n   <td style=\"text-align:left;\"> 25,361 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 100.000 </td>\n   <td style=\"text-align:right;\"> 19.341 </td>\n   <td style=\"text-align:right;\"> 4185 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Snyder County </td>\n   <td style=\"text-align:left;\"> 36,745 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 40.000 </td>\n   <td style=\"text-align:right;\"> 13.474 </td>\n   <td style=\"text-align:right;\"> 27456 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Bradford County </td>\n   <td style=\"text-align:left;\"> 59,250 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 40.000 </td>\n   <td style=\"text-align:right;\"> 12.210 </td>\n   <td style=\"text-align:right;\"> 23832 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Clearfield County </td>\n   <td style=\"text-align:left;\"> 74,316 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 28.571 </td>\n   <td style=\"text-align:right;\"> 11.134 </td>\n   <td style=\"text-align:right;\"> 34432 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Huntingdon County </td>\n   <td style=\"text-align:left;\"> 38,896 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 25.000 </td>\n   <td style=\"text-align:right;\"> 7.981 </td>\n   <td style=\"text-align:right;\"> 18514 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Northumberland County </td>\n   <td style=\"text-align:left;\"> 87,265 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 20.000 </td>\n   <td style=\"text-align:right;\"> 10.794 </td>\n   <td style=\"text-align:right;\"> 27608 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Crawford County </td>\n   <td style=\"text-align:left;\"> 79,317 </td>\n   <td style=\"text-align:right;\"> 8 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 12.500 </td>\n   <td style=\"text-align:right;\"> 6.455 </td>\n   <td style=\"text-align:right;\"> 36036 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Chester County </td>\n   <td style=\"text-align:left;\"> 525,607 </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 6.667 </td>\n   <td style=\"text-align:right;\"> 5.273 </td>\n   <td style=\"text-align:right;\"> 165947 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Cumberland County </td>\n   <td style=\"text-align:left;\"> 251,371 </td>\n   <td style=\"text-align:right;\"> 25 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 4.000 </td>\n   <td style=\"text-align:right;\"> 6.531 </td>\n   <td style=\"text-align:right;\"> 144521 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Dauphin County </td>\n   <td style=\"text-align:left;\"> 280,910 </td>\n   <td style=\"text-align:right;\"> 25 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 4.000 </td>\n   <td style=\"text-align:right;\"> 4.464 </td>\n   <td style=\"text-align:right;\"> 136085 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> York County </td>\n   <td style=\"text-align:left;\"> 451,220 </td>\n   <td style=\"text-align:right;\"> 36 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 2.778 </td>\n   <td style=\"text-align:right;\"> 5.379 </td>\n   <td style=\"text-align:right;\"> 179014 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Somerset County </td>\n   <td style=\"text-align:left;\"> 68,975 </td>\n   <td style=\"text-align:right;\"> 6 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 3.504 </td>\n   <td style=\"text-align:right;\"> 22463 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Centre County </td>\n   <td style=\"text-align:left;\"> 137,615 </td>\n   <td style=\"text-align:right;\"> 9 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 4.223 </td>\n   <td style=\"text-align:right;\"> 38866 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Clinton County </td>\n   <td style=\"text-align:left;\"> 36,080 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 8.046 </td>\n   <td style=\"text-align:right;\"> 15682 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Allegheny County </td>\n   <td style=\"text-align:left;\"> 1,204,750 </td>\n   <td style=\"text-align:right;\"> 108 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 2.574 </td>\n   <td style=\"text-align:right;\"> 482906 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Westmoreland County </td>\n   <td style=\"text-align:left;\"> 345,888 </td>\n   <td style=\"text-align:right;\"> 36 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 4.661 </td>\n   <td style=\"text-align:right;\"> 146373 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Franklin County </td>\n   <td style=\"text-align:left;\"> 154,791 </td>\n   <td style=\"text-align:right;\"> 12 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 3.948 </td>\n   <td style=\"text-align:right;\"> 65501 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Bucks County </td>\n   <td style=\"text-align:left;\"> 636,706 </td>\n   <td style=\"text-align:right;\"> 50 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 3.748 </td>\n   <td style=\"text-align:right;\"> 280864 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Warren County </td>\n   <td style=\"text-align:left;\"> 37,525 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 8.382 </td>\n   <td style=\"text-align:right;\"> 5066 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Montgomery County </td>\n   <td style=\"text-align:left;\"> 838,834 </td>\n   <td style=\"text-align:right;\"> 54 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 2.205 </td>\n   <td style=\"text-align:right;\"> 279603 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Erie County </td>\n   <td style=\"text-align:left;\"> 256,390 </td>\n   <td style=\"text-align:right;\"> 32 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 3.739 </td>\n   <td style=\"text-align:right;\"> 135226 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Washington County </td>\n   <td style=\"text-align:left;\"> 204,089 </td>\n   <td style=\"text-align:right;\"> 15 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 3.934 </td>\n   <td style=\"text-align:right;\"> 76139 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Delaware County </td>\n   <td style=\"text-align:left;\"> 553,942 </td>\n   <td style=\"text-align:right;\"> 29 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 2.987 </td>\n   <td style=\"text-align:right;\"> 144998 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Wayne County </td>\n   <td style=\"text-align:left;\"> 47,948 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 5.051 </td>\n   <td style=\"text-align:right;\"> 17029 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Northampton County </td>\n   <td style=\"text-align:left;\"> 303,453 </td>\n   <td style=\"text-align:right;\"> 26 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 4.422 </td>\n   <td style=\"text-align:right;\"> 134840 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Monroe County </td>\n   <td style=\"text-align:left;\"> 164,984 </td>\n   <td style=\"text-align:right;\"> 8 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 7.279 </td>\n   <td style=\"text-align:right;\"> 40647 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Clarion County </td>\n   <td style=\"text-align:left;\"> 35,766 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 7.073 </td>\n   <td style=\"text-align:right;\"> 4525 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Armstrong County </td>\n   <td style=\"text-align:left;\"> 64,293 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 6.358 </td>\n   <td style=\"text-align:right;\"> 20540 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Juniata County </td>\n   <td style=\"text-align:left;\"> 23,140 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 8.809 </td>\n   <td style=\"text-align:right;\"> 5560 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Lancaster County </td>\n   <td style=\"text-align:left;\"> 540,847 </td>\n   <td style=\"text-align:right;\"> 50 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 4.511 </td>\n   <td style=\"text-align:right;\"> 274969 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Perry County </td>\n   <td style=\"text-align:left;\"> 45,501 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 8.840 </td>\n   <td style=\"text-align:right;\"> 25008 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Greene County </td>\n   <td style=\"text-align:left;\"> 32,107 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 9.286 </td>\n   <td style=\"text-align:right;\"> 5359 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Philadelphia County </td>\n   <td style=\"text-align:left;\"> 1,534,829 </td>\n   <td style=\"text-align:right;\"> 103 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 1.122 </td>\n   <td style=\"text-align:right;\"> 471644 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Fayette County </td>\n   <td style=\"text-align:left;\"> 122,435 </td>\n   <td style=\"text-align:right;\"> 12 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 5.952 </td>\n   <td style=\"text-align:right;\"> 52205 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Indiana County </td>\n   <td style=\"text-align:left;\"> 77,912 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 3.164 </td>\n   <td style=\"text-align:right;\"> 19998 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Schuylkill County </td>\n   <td style=\"text-align:left;\"> 136,306 </td>\n   <td style=\"text-align:right;\"> 10 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 5.955 </td>\n   <td style=\"text-align:right;\"> 47762 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Jefferson County </td>\n   <td style=\"text-align:left;\"> 43,360 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 3.682 </td>\n   <td style=\"text-align:right;\"> 14537 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Columbia County </td>\n   <td style=\"text-align:left;\"> 61,190 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 8.047 </td>\n   <td style=\"text-align:right;\"> 21643 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Cambria County </td>\n   <td style=\"text-align:left;\"> 125,751 </td>\n   <td style=\"text-align:right;\"> 13 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 5.220 </td>\n   <td style=\"text-align:right;\"> 52575 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Elk County </td>\n   <td style=\"text-align:left;\"> 30,357 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 5.468 </td>\n   <td style=\"text-align:right;\"> 15249 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Venango County </td>\n   <td style=\"text-align:left;\"> 48,968 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 8.728 </td>\n   <td style=\"text-align:right;\"> 12686 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Mercer County </td>\n   <td style=\"text-align:left;\"> 103,241 </td>\n   <td style=\"text-align:right;\"> 10 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 4.375 </td>\n   <td style=\"text-align:right;\"> 43331 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Tioga County </td>\n   <td style=\"text-align:left;\"> 40,144 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 8.561 </td>\n   <td style=\"text-align:right;\"> 17895 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Susquehanna County </td>\n   <td style=\"text-align:left;\"> 38,026 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 7.602 </td>\n   <td style=\"text-align:right;\"> 12544 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Fulton County </td>\n   <td style=\"text-align:left;\"> 14,482 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 7.194 </td>\n   <td style=\"text-align:right;\"> 14482 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Mckean County </td>\n   <td style=\"text-align:left;\"> 37,353 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 14.160 </td>\n   <td style=\"text-align:right;\"> 5054 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Beaver County </td>\n   <td style=\"text-align:left;\"> 164,101 </td>\n   <td style=\"text-align:right;\"> 9 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 4.842 </td>\n   <td style=\"text-align:right;\"> 43615 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Lawrence County </td>\n   <td style=\"text-align:left;\"> 83,246 </td>\n   <td style=\"text-align:right;\"> 8 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 3.467 </td>\n   <td style=\"text-align:right;\"> 26832 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Lehigh County </td>\n   <td style=\"text-align:left;\"> 366,088 </td>\n   <td style=\"text-align:right;\"> 27 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 3.115 </td>\n   <td style=\"text-align:right;\"> 152497 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Blair County </td>\n   <td style=\"text-align:left;\"> 118,005 </td>\n   <td style=\"text-align:right;\"> 9 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 2.836 </td>\n   <td style=\"text-align:right;\"> 38284 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Lackawanna County </td>\n   <td style=\"text-align:left;\"> 207,584 </td>\n   <td style=\"text-align:right;\"> 16 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 4.051 </td>\n   <td style=\"text-align:right;\"> 83582 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Montour County </td>\n   <td style=\"text-align:left;\"> 17,268 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 1.141 </td>\n   <td style=\"text-align:right;\"> 13466 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Butler County </td>\n   <td style=\"text-align:left;\"> 190,460 </td>\n   <td style=\"text-align:right;\"> 18 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 6.679 </td>\n   <td style=\"text-align:right;\"> 91244 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Adams County </td>\n   <td style=\"text-align:left;\"> 100,831 </td>\n   <td style=\"text-align:right;\"> 8 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 5.852 </td>\n   <td style=\"text-align:right;\"> 42363 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Bedford County </td>\n   <td style=\"text-align:left;\"> 47,034 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 7.495 </td>\n   <td style=\"text-align:right;\"> 22509 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Carbon County </td>\n   <td style=\"text-align:left;\"> 64,316 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 4.200 </td>\n   <td style=\"text-align:right;\"> 33720 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Berks County </td>\n   <td style=\"text-align:left;\"> 416,342 </td>\n   <td style=\"text-align:right;\"> 25 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 3.727 </td>\n   <td style=\"text-align:right;\"> 127998 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Mifflin County </td>\n   <td style=\"text-align:left;\"> 45,377 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 5.964 </td>\n   <td style=\"text-align:right;\"> 21391 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Lebanon County </td>\n   <td style=\"text-align:left;\"> 139,845 </td>\n   <td style=\"text-align:right;\"> 15 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 4.196 </td>\n   <td style=\"text-align:right;\"> 80692 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Union County </td>\n   <td style=\"text-align:left;\"> 33,756 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 4.830 </td>\n   <td style=\"text-align:right;\"> 17096 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Lycoming County </td>\n   <td style=\"text-align:left;\"> 107,717 </td>\n   <td style=\"text-align:right;\"> 9 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 3.111 </td>\n   <td style=\"text-align:right;\"> 48483 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Luzerne County </td>\n   <td style=\"text-align:left;\"> 315,008 </td>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 4.226 </td>\n   <td style=\"text-align:right;\"> 94118 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Potter County </td>\n   <td style=\"text-align:left;\"> 16,025 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 0.662 </td>\n   <td style=\"text-align:right;\"> 4031 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Sullivan County </td>\n   <td style=\"text-align:left;\"> 5,510 </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Cameron County </td>\n   <td style=\"text-align:left;\"> 4,420 </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Forest County </td>\n   <td style=\"text-align:left;\"> 4,399 </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\ndf_removed$percentage=df_removed$per*100\nggplot(df_removed) +\n  geom_sf(aes(fill = percentage), color = \"white\")+\n  geom_sf(data = host_proj, aes(color = \"Hospital\"),size=1)+\n  scale_fill_viridis_c(\n    name = \"Percentage of vulnerable tracts\",\n    option = \"magma\"\n  ) +\n  scale_color_manual(\n    name=\"\",\n    values = c(\"Hospital\" = \"red\")\n  )+\n  labs(\n    title = \"Vulnerable Tracts and Hospital Locations in Pennsylvania\",\n    subtitle=\"Data Source: ACS 5-Year Census Data\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_tim_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\ndist_final_map=dist_final%>%\n  group_by(GEOID)%>%\n  summarise(\n    vulnerable=n(),\n    underserved=sum(indi==1),\n    per=underserved/vulnerable,\n    avg_dis=mean(dis_to_tract),\n    vulner_pop=sum(populationE)\n  )\n\ndist_final_map2=vulnerable_proj%>%\n  left_join(dist_final_map,by=\"GEOID\")\n\nggplot() +\n  geom_sf(data = census_tracts, color=\"black\")+\n  geom_sf(data=dist_final_map2,fill=\"red\",aes(color=\"Vulnerable Tract\"))+\n  geom_sf(data = host_proj, aes(color = \"Hospital\"),size=1)+\n  geom_sf(data = df_removed,fill= NA,aes(color = \"County Boundary\"),size=6, alpha= 1)+\n  scale_fill_viridis_c(\n    name = \"Percentage of vulnerable tracts\",\n    option = \"magma\"\n  ) +\n  scale_color_manual(\n    name=\"\",\n    values = c(\"Hospital\" = \"black\",\"Vulnerable Tract\"=\"black\",\"County Boundary\"=\"yellow\")\n  )+\n  labs(\n    title = \"Vulnerable Tracts and Hospital Locations in Pennsylvania\",\n    subtitle = \"Data Source: ACS 5-Year Census Data\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_tim_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\nggplot(dist_final, aes(x = dis_to_tract,weight=populationE)) +\n  geom_histogram(binwidth = 1, color = \"black\", fill = \"skyblue\") +\n   scale_y_continuous(labels = comma) +\n  labs(\n    title = \"Distribution of Distances to Hospitals for Population\",\n    x = \"Distance (Miles)\",\n    y = \"Population\",\n    subtitle = \"The distribution is left-skewed, with most people located relatively close to the nearest hospital.\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5, size = 14, face = \"bold\"),\n    axis.title = element_text(size = 12)\n  )\n```\n\n::: {.cell-output-display}\n![](assignment2_tim_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\nlibrary(httr)\nlibrary(jsonlite)\n\ntree=st_read(\"C:/Users/wensh/Desktop/MUSA5080/week-04/data/ppr_tree_inventory_2024/ppr_tree_inventory_2024.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `ppr_tree_inventory_2024' from data source \n  `C:\\Users\\wensh\\Desktop\\MUSA5080\\week-04\\data\\ppr_tree_inventory_2024\\ppr_tree_inventory_2024.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 151713 features and 6 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -8380434 ymin: 4847791 xmax: -8344373 ymax: 4885938\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\nparkl=st_read(\"C:/Users/wensh/Desktop/MUSA5080/week-04/data/PPR_Program_Sites.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PPR_Program_Sites' from data source \n  `C:\\Users\\wensh\\Desktop\\MUSA5080\\week-04\\data\\PPR_Program_Sites.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 171 features and 10 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -75.2563 ymin: 39.90444 xmax: -74.96944 ymax: 40.12284\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\npark_proj=parkl%>%st_transform(3365)\ntree_proj=tree%>%st_transform(3365)\nsummary(park_proj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    OBJECTID       PARK_NAME          DPP_ASSET_ID  PROGRAM_TYPE      \n Min.   : 807.0   Length:171         Min.   :   4   Length:171        \n 1st Qu.: 993.5   Class :character   1st Qu.:1826   Class :character  \n Median :1036.0   Mode  :character   Median :1891   Mode  :character  \n Mean   :1027.6                      Mean   :1795                     \n 3rd Qu.:1078.5                      3rd Qu.:1952                     \n Max.   :1121.0                      Max.   :3479                     \n  SITE_CLASS          BUILDING             GYM            LABEL_NUMBER      \n Length:171         Length:171         Length:171         Length:171        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n   COMMENTS         DATA_SOURCE                 geometry  \n Length:171         Length:171         POINT        :171  \n Class :character   Class :character   epsg:3365    :  0  \n Mode  :character   Mode  :character   +proj=lcc ...:  0  \n                                                          \n                                                          \n                                                          \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(tree_proj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    objectid       tree_name            tree_dbh           year          \n Min.   :     1   Length:151713      Min.   :  -3.00   Length:151713     \n 1st Qu.: 37929   Class :character   1st Qu.:   4.00   Class :character  \n Median : 75857   Mode  :character   Median :  10.00   Mode  :character  \n Mean   : 75857                      Mean   :  13.09                     \n 3rd Qu.:113785                      3rd Qu.:  20.00                     \n Max.   :151713                      Max.   :1118.00                     \n                                     NA's   :16                          \n     loc_y           loc_x                 geometry     \n Min.   :39.87   Min.   :-75.28   POINT        :151713  \n 1st Qu.:39.95   1st Qu.:-75.20   epsg:3365    :     0  \n Median :39.98   Median :-75.17   +proj=lcc ...:     0  \n Mean   :39.99   Mean   :-75.16                         \n 3rd Qu.:40.03   3rd Qu.:-75.14                         \n Max.   :40.14   Max.   :-74.96                         \n                                                        \n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\n\n  I choose both tree and park data in Philadelphia because I want to study if different tracts have equal access to green spaces\n\n- What is the data source and date?\n\n  Both of them are from Opendataphilly, tree data is from 2024 while park data is from 2022\n\n- How many features does it contain?\n\n  there are 151,713 features in tree data and 171 features in park data\n\n- What CRS is it in? Did you need to transform it?\n\n  Both of the CRS are WGS84 at first and I transform it to espg 3365\n\n---\n\n2. **Pose a research question**\n\nWrite a clear research statement that your analysis will answer.\n\n**Do minority and low income census tracts have the same access to green spaces and enjoy same tree canopy as others?**\n\n---\n\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\n#get philly census data\nphilly=get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  county = \"101\",\n  year = 2023,\n  survey = \"acs5\",\n  variables =c(population=\"DP02_0018\",age=\"DP05_0023\",income=\"DP03_0062\"),\n  geometry = TRUE,\n  output=\"wide\"\n)\n#reproject census data\nphilly_project=philly%>%\n  st_transform(3365)\n#spatial join census data with tree counts\nphilly_tree = philly_project%>%\n  mutate(tree_count = lengths(st_contains(., tree_proj)))\n\n#calculate the distance between tract and parks\ntract_center=st_centroid(philly_project)\ndist_park <- tract_center %>%\n  mutate(\n    dis_to_tract = apply(\n      st_distance(tract_center, park_proj),\n      1,\n      min\n    ) *0.000189\n  )\n\n#merge tree counts and distance to park\ndist_final_philly = dist_park%>%\n  st_drop_geometry()%>%\n  select(GEOID,dis_to_tract)\nfinal_philly = philly_tree%>%\n  left_join(dist_final_philly,by=\"GEOID\")\n\n#calculate tree per area in census tract\nfinal_philly = final_philly%>%\n  mutate(area=st_area(geometry))%>%\n  mutate(tree_per=as.numeric(tree_count/area))\n  \n#normalize both distance to park and tree per area\nnormalize_to_0_1 <- function(vec) {\n  min_val <- min(vec, na.rm = TRUE)\n  max_val <- max(vec, na.rm = TRUE)\n  normalized_vec <- (vec - min_val) / (max_val - min_val)\n  return(normalized_vec)\n}\n\n#calculate the final index (park 75% weight and tree 25% weight)\nfinal_philly=final_philly%>%\n  mutate(normalize_tree=normalize_to_0_1(tree_per))%>%\n  mutate(normalize_park=normalize_to_0_1(dis_to_tract))%>%\n  mutate(index=0.75*normalize_park+0.25*normalize_tree)\n\n#map the results\nggplot(final_philly) +\n  geom_sf(aes(fill = index), color = \"white\")+\n  scale_fill_viridis_c(\n    name = \"Green Space Index\",\n    option = \"magma\"\n  ) +\n  labs(\n    title = \"Green Space Index in Pennsylvania\",\n    subtitle = \"Calculated based on distance to park and tree by area\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](assignment2_tim_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\nBased on the map, it is clear that Richer areas (eg. Center City) obtain a higher green space index, while poor neighborhoods (especially in the north such as Kensington) have a low green space index. As a result, minority and poor neighborhood indeed have less access to green space. \n\nAnother finding is suburban area tend to have larger green space index compared to downtown, which makes sense as there are more spaces to plant trees/parks at suburb comapred to downtown.\n\n\n## Finally - A few comments about your incorporation of feedback!\n\nFirst I remove the extra instruction text in my homework such as the submission requirement in the end, I also remove the [] in my answer. \n\nSecond, I used round() function to make my table look cleaner\n\n\n\n",
    "supporting": [
      "assignment2_tim_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}