{
  "hash": "ba11d173d0ed466b6bbe2c1527c5b234",
  "result": {
    "markdown": "---\ntitle: \"Technical Appendix\"\nformat: \n  html:\n    toc: true\n    toc-location: left\n    code-fold: show\n    theme: cosmo\n---\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tidycensus' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tidyverse' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.3     ✔ readr     2.1.4\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   4.0.0     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.0\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n\nAttaching package: 'scales'\n\n\nThe following object is masked from 'package:purrr':\n\n    discard\n\n\nThe following object is masked from 'package:readr':\n\n    col_factor\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'sf' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLinking to GEOS 3.11.2, GDAL 3.8.2, PROJ 9.3.1; sf_use_s2() is TRUE\nTo enable caching of data, set `options(tigris_use_cache = TRUE)`\nin your R script or .Rprofile.\nhere() starts at C:/Users/Tim Wen/Documents/GitHub/portfolio-setup-wenshaoting6-ui\nData (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright.\nCheck the package website, https://docs.ropensci.org/osmextract/, for more details.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'spatstat.geom' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: spatstat.data\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'spatstat.data' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: spatstat.univar\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'spatstat.univar' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nspatstat.univar 3.1-2\nspatstat.geom 3.3-6\n\nAttaching package: 'spatstat.geom'\n\nThe following object is masked from 'package:patchwork':\n\n    area\n\nThe following object is masked from 'package:scales':\n\n    rescale\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'spatstat' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: spatstat.random\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'spatstat.random' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nspatstat.random 3.3-3\nLoading required package: spatstat.explore\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'spatstat.explore' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: nlme\n\nAttaching package: 'nlme'\n\nThe following object is masked from 'package:dplyr':\n\n    collapse\n\nspatstat.explore 3.4-2\nLoading required package: spatstat.model\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'spatstat.model' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: rpart\nspatstat.model 3.3-5\nLoading required package: spatstat.linnet\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'spatstat.linnet' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nspatstat.linnet 3.2-5\n\nspatstat 3.3-2 \nFor an introduction to spatstat, type 'beginner' \n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'terra' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nterra 1.7.83\n\nAttaching package: 'terra'\n\nThe following objects are masked from 'package:spatstat.geom':\n\n    area, delaunay, is.empty, rescale, rotate, shift, where.max,\n    where.min\n\nThe following object is masked from 'package:patchwork':\n\n    area\n\nThe following object is masked from 'package:tigris':\n\n    blocks\n\nThe following object is masked from 'package:scales':\n\n    rescale\n\nThe following object is masked from 'package:knitr':\n\n    spin\n\nThe following object is masked from 'package:tidyr':\n\n    extract\n\n\nAttaching package: 'jsonlite'\n\nThe following object is masked from 'package:purrr':\n\n    flatten\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'FNN' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nPlease cite as: \n\n Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.\n R package version 5.2.3. https://CRAN.R-project.org/package=stargazer \n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'car' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: carData\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'carData' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'car'\n\nThe following object is masked from 'package:spatstat.model':\n\n    bc\n\nThe following object is masked from 'package:spatstat.geom':\n\n    ellipse\n\nThe following object is masked from 'package:dplyr':\n\n    recode\n\nThe following object is masked from 'package:purrr':\n\n    some\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'lmtest' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: zoo\n\nAttaching package: 'zoo'\n\nThe following object is masked from 'package:terra':\n\n    time<-\n\nThe following objects are masked from 'package:base':\n\n    as.Date, as.Date.numeric\n```\n:::\n:::\n\n\n# PHASE 1: DATA PREPARATION\n\n## 1.1 Load and Philadelphia house sales data\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load Philly Property Sales data\nphl_sales <- read_csv(here(\"data\", \"raw\", \"opa_properties_public.csv\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: One or more parsing issues, call `problems()` on your data frame for details,\ne.g.:\n  dat <- vroom(...)\n  problems(dat)\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 583802 Columns: 79\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr  (38): basements, beginning_point, book_and_page, building_code, buildin...\ndbl  (31): category_code, census_tract, depth, exempt_building, exempt_land,...\nlgl   (7): cross_reference, date_exterior_condition, mailing_address_2, mark...\ndttm  (3): assessment_date, recording_date, sale_date\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n:::\n\n\n### Filter to residential properties, 2023-2024 sales\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check data types\n# glimpse(phl_sales)\n\nphl_sales_res_23_24 <- phl_sales |>\n  filter(\n    category_code == 1, # Residential\n    year(sale_date) %in% c(2023, 2024), # 2023-24 sales\n    !is.na(category_code) & !is.na(sale_date) # Handle nulls\n  )\n```\n:::\n\n\n### Remove obvious errors\n\n::: {.cell}\n\n```{.r .cell-code}\nphl_sales_clean <- phl_sales_res_23_24 |>\n  filter(\n    # Some sale_price are unrealistically too low ($0, $1 etc.)\n    sale_price >= 10000,\n    # Exclude homes with 0 bathrooms\n    number_of_bathrooms > 0,\n    # Some areas are unrealistically low (0, 1, etc.)\n    total_area > 1,\n    # Some 0's remain in total_liveable_area after first area filter\n    total_livable_area > 0,\n    # Filter our unrealistic year built\n    year_built >= 1750\n    ) \n```\n:::\n\n\n### Handle missing values\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check how many features have NA values\n# sum(is.na(phl_sales_clean$number_of_bedrooms))\n# sum(is.na(phl_sales_clean$number_of_bathrooms))\n# sum(is.na(phl_sales_clean$total_livable_area))\n# sum(is.na(phl_sales_clean$year_built))\n\n# Remove the 2 observations with NA values for number of bedrooms\nphl_sales_clean <- phl_sales_clean |>\n  filter(\n    !is.na(number_of_bedrooms)\n  )\n```\n:::\n\n\n### Preliminary Feature Engineering: Age = sale date - year built\n\n::: {.cell}\n\n```{.r .cell-code}\nphl_sales_clean <- phl_sales_clean |>\n  mutate(\n    sale_year = year(sale_date),\n    age = sale_year - year_built\n  )\n```\n:::\n\n\n### Document all cleaning decisions\n\n\n- Our methodology for cleaning the Philadelphia home sales data is to focus on the features used in our model. As a group, we decided on the following independent variables to consider in our data exploration and model building to be: number of bathrooms, number of bedrooms, total livable area, and year built. We recognize that there is some risk of collinearity between these structural features, which will later be monitored and addressed if needed in the model building stage. Additionally, we also had to clean the sales price column since this is the variable we aim to predict in our model.\n\n\n- Filter for only **residential properties** & **sales made in 2023-24** (per instructions).\n\n\n- Filter for **realistic sales price** >= $10,000.\n\n\n- Filter for houses with **at least 1 bathroom**. We will keep observations where **number of bedrooms = 0** as this likely signifies a studio apartment. However, it is not feasible for homes to have zero bathrooms, so we will enforce a constraint that a home must have at least 1 bathroom to preserve data integrity.\n\n\n- Filter for **realistic total area** > 1 sq ft & **realistic total livable area** > 0 sq ft.\n\n\n- Filter for **year built** >= 1750 (some homes were built in year 0).\n\n\n- **Handle missing values:** We removed any missing values in our dependent variable of sales price, since it is crucial we have a true and accurate measure for prediction. We also checked which of our predictor variables had NA values after filtering. Only number of bedrooms had 2 remaining NA values. The rest had no NA values. To remedy this, we will remove the 2 observations from our data. Note, if there was substantial missing values in our predictors, we could use strategies such as imputing the NA values with the mean or median to use when building our model. \n\n\n- **Preliminary feature engineering:** Rather than using year built in our Automated Valuation Model, it makes more sense to create a new variable **age** that is equal to the sale date minus the year built. The **age** variable is often easier to interpret in exploratory plots with the newer houses appearing on the left and older ones on the right. This is primarily a stylistic preference: the overall pattern of the data will remain the same but mirrored.\n\n\n## 1.2 Load Secondary Data\n\n### Census\n\nPurpose: Pull demographic and housing data at the census tract level for Philadelphia from the 2023 5-year ACS. This data will provide predictors for neighborhood characteristics in our modeling.\n\nVariables Collected:\n\nMedian household income (B19013)\n\nPercentage of family households (B11001)\n\nEducation attainment: percent of population 25+ with a bachelor’s degree or higher (B15003)\n\nHousing vacancy rate (B25002)\n\nRacial composition: percent white (B02001)\n\n\n\n\n\n#### Load Philly Census Data from Previously Retrieved Files\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Relative to project root\ncensus_path <- here(\"data\", \"Philly Census\")\n\ncensus_csv_path <- file.path(census_path, \"philly_tract_metrics.csv\")\ncensus_shp_path <- file.path(census_path, \"philly_tract.shp\")\n\n# Csv with census tract Geo IDs and metrics\nphilly_censustract <- read_csv(census_csv_path, show_col_types = FALSE)\n\n# Shp File including geometry\nphilly_tract_sf <- st_read(census_shp_path, quiet = TRUE)\n```\n:::\n\n\n#### Observe Summary Statistics from target metrics.x\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnumeric_vars <- c(\"median_income\", \"pct_white\", \"pct_bachelors\", \"pct_vacant\")\nphilly_censustract %>%\n  select(all_of(numeric_vars)) %>%\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n median_income      pct_white      pct_bachelors      pct_vacant     \n Min.   : 13721   Min.   : 0.000   Min.   : 1.504   Min.   :  0.000  \n 1st Qu.: 42469   1st Qu.: 8.826   1st Qu.:16.094   1st Qu.:  5.366  \n Median : 60817   Median :34.740   Median :28.426   Median :  8.516  \n Mean   : 66877   Mean   :37.944   Mean   :36.325   Mean   :  9.844  \n 3rd Qu.: 85298   3rd Qu.:64.202   3rd Qu.:55.345   3rd Qu.: 12.801  \n Max.   :192727   Max.   :95.513   Max.   :96.632   Max.   :100.000  \n NA's   :27       NA's   :17       NA's   :17       NA's   :19       \n```\n:::\n:::\n\nA quick check of the census variables reveals some missing values and lower than epected values in median income. We will note this information but retain the missing values for now to maintain the full pitcure of census blocks.\n\n\n### Cleaning Methodology (Census)\n\nMedian income: Selected only the estimate column and renamed it for clarity.\n\nHousehold composition: Pivoted ACS table to wide format, then calculated total households and family households.\n\nEducation: Pivoted to wide format, summed relevant categories to compute percent of population with a bachelor’s degree or higher.\n\nVacancy: Pivoted to wide format, calculated percent of homes vacant (vacant_units / total_units * 100).\n\nRacial composition: Pivoted to wide format, computed percent white.\n\nMerging: Combined all datasets by GEOID to create a single dataframe philly_blockgroup with all variables.\n\nGeometry: Pulled census tract shapefiles with ACS geometry and merged with philly_blockgroup to create philly_bg_map.\n\n### Neighborhood (Polygon)\n\nReading in Philadelphia Neighborhoods as a shp object. This will allow us to aggregate data on neighborhoods to identify catagorical metrics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nneighborhood_folder <- here(\"data\", \"philadelphia-neighborhoods\")\nneighborhood_path   <- file.path(neighborhood_folder, \"philadelphia-neighborhoods.shp\")\n\n# Read the shapefile\nphilly_neighborhoods <- st_read(neighborhood_path, quiet = TRUE)\n\nhead(philly_neighborhoods)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSimple feature collection with 6 features and 5 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -75.23049 ymin: 39.98491 xmax: -75.0156 ymax: 40.11269\nGeodetic CRS:  WGS 84\n             NAME         LISTNAME         MAPNAME Shape_Leng Shape_Area\n1      BRIDESBURG       Bridesburg      Bridesburg   27814.55   44586264\n2       BUSTLETON        Bustleton       Bustleton   48868.46  114050424\n3      CEDARBROOK       Cedarbrook      Cedarbrook   20021.42   24871745\n4   CHESTNUT_HILL    Chestnut Hill   Chestnut Hill   56394.30   79664975\n5      EAST_FALLS       East Falls      East Falls   27400.78   40576888\n6 MOUNT_AIRY_EAST Mount Airy, East East Mount Airy   28845.55   43152470\n                        geometry\n1 POLYGON ((-75.06773 40.0054...\n2 POLYGON ((-75.0156 40.09487...\n3 POLYGON ((-75.18848 40.0727...\n4 POLYGON ((-75.21221 40.0860...\n5 POLYGON ((-75.18476 40.0282...\n6 POLYGON ((-75.18087 40.0432...\n```\n:::\n:::\n\n\n\n### Commercial and office points of interests (Amenities)(alternative in the next section if you do not want to download pbf data)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# downloading osm data from geofabrik:https://download.geofabrik.de/north-america/us-northeast.html\n\n#input_pbf <- \"the pdf file downloaded from the link above\"\n\n\n# get boundary of Philadelphia County\npa_counties <- counties(state = \"PA\", year = 2023)\n\n# Filter to Philadelphia County\nphilly_boundary <- subset(pa_counties, NAME == \"Philadelphia\")\n\n# read the full OSM PBF (you can select layer types like points, lines, polygons)\npoi <- oe_read(input_pbf, \n                       boundary = philly_boundary, \n                       boundary_type = \"clipsrc\", \n                       layer = \"points\")  # or \"lines\" / \"multipolygons\"\n\n\nkeywords <- c(\"shop\",\"amenity\",\"office\",\"historic\",\"tourism\",\"healthcare\",\n              \"building\",\"leisure\")\npattern <- paste0(keywords, collapse = \"|\")\n\n# ==== Filter by 'other_tags' ====\nif (\"other_tags\" %in% names(poi)) {\n  poi$other_tags <- iconv(as.character(poi$other_tags), from = \"\", to = \"UTF-8\", sub = \"\")\n  poi$other_tags[is.na(poi$other_tags)] <- \"\"\n  \n  poi_filtered <- poi %>%\n    filter(grepl(pattern, other_tags, ignore.case = TRUE))\n  \n  cat(\"filtered POIs found:\", nrow(poi_filtered), \"of\", nrow(poi), \"\\n\")\n  \n} \n```\n:::\n\n\n### Alternative: filtered POI if you donot want to download osm data\n\n::: {.cell}\n\n```{.r .cell-code}\npoi_path <- here(\"data\", \"filtered poi\")\npoi_shp_path=file.path(poi_path, \"philadelphia_poi_filtered.shp\")\npoi=st_read(poi_shp_path)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nReading layer `philadelphia_poi_filtered' from data source \n  `C:\\Users\\Tim Wen\\Documents\\GitHub\\portfolio-setup-wenshaoting6-ui\\data\\filtered poi\\philadelphia_poi_filtered.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 11161 features and 10 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -75.27472 ymin: 39.87383 xmax: -74.95777 ymax: 40.13445\nGeodetic CRS:  WGS 84\n```\n:::\n:::\n\n\n### Kernel Density Rasters (Economic activities density)\nInstead of using distance to CBD, we extracted commercial and office points of interests from OpenStreetMap (OSM), and we opreate a Kernel Density Estimation (KDE) with a bandwidth of 300 meters. By doing that, we manage to get a surface of density of economic activities across the whole city. The higher the KDE value is, the more economic activities it will be, implying a higher likelyhood of the area as a city centers.\n\nThere are several benefits using this approach compared to distance to CBD. First, with the development of suburbanization, even within the context of Philadelphia County, there is still a shift from monocentric model to polycentric model, meaning there multiple centers/subcenters. Using one CBD fail to capture these subcenters, which may also influence housing price. Second, CBD is an area rather than a point, distance method fail to capture this while the continuous surface computed by KDE would have a value of economic activities across the whole city. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# get boundary of Philadelphia County\npa_counties <- counties(state = \"PA\", year = 2023)\n\n# Filter to Philadelphia County\nphilly_boundary <- subset(pa_counties, NAME == \"Philadelphia\")\n\nphilly_boundary <- st_transform(philly_boundary, 2272)  \npoi <- st_transform(poi, 2272)\n# ==== Prepare point pattern ====\n# Convert sf points to spatstat ppp object\nwin <- as.owin(st_union(philly_boundary))  # window from county boundary\ncoords <- st_coordinates(poi)\npp <- ppp(x = coords[,1], y = coords[,2], window = win)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: data contain duplicated points\n```\n:::\n\n```{.r .cell-code}\n# ==== Run Kernel Density Estimation ====\n# Sigma = bandwidth in map units (here, meters)\ndensity_map <- density.ppp(pp, sigma = 300* 3.28084, edge = TRUE, at = \"pixels\",eps = c(100, 100))\n\n# ==== Convert to raster ====\nr_Economic <- rast(density_map)\ncrs(r_Economic) <- st_crs(philly_boundary)$proj4string\nr_Economic <- mask(r_Economic, vect(philly_boundary))\n```\n:::\n\n\n### Education\n\nWe used two datasets from OpenDataPhilly.com to identify schools geolocation and populated the metrics off Attendance percent and Withdrawal volumes from those schools.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Relative to project root\neducation_path <- here(\"data\", \"Education\")\n\neducation_csv_path <- file.path(education_path, \"philadelphia_schools.csv\")\neducation_shp_path <- file.path(education_path, \"Schools Shape\", \"Schools.shp\")\n\n# Csv with School Names and metrics\nphilly_schools <- read_csv(education_csv_path, show_col_types = FALSE)\n\n# Shp File including geometry\nphilly_schools_sf <- st_read(education_shp_path, quiet = TRUE)\n```\n:::\n\n\nWe joined the csv file containing the metrics with the shp file containing geoloaction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Joining Schools csv metrics to shp file. Joined on 'location_i' (shp) and 'School_code (csv)\n# Keeping metrics for Attendance and Withdrawals\n\n# Select relevant metrics from CSV\nschool_metrics <- philly_schools %>%\n  select(School_code, Attendance, Withdrawals) %>%\n  mutate(School_code = as.character(School_code))\n\nphilly_schools_sf <- philly_schools_sf %>%\n  left_join(school_metrics,\n            by = c(\"location_i\" = \"School_code\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nphilly_schools_sf_clean <- philly_schools_sf %>%\n  filter(!is.na(Attendance) & !is.na(Withdrawals))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(philly_schools_sf_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"aun\"         \"school_num\"  \"location_i\"  \"school_nam\"  \"school_n_1\" \n [6] \"street_add\"  \"zip_code\"    \"phone_numb\"  \"grade_leve\"  \"grade_org\"  \n[11] \"enrollment\"  \"type\"        \"type_speci\"  \"objectid\"    \"Attendance\" \n[16] \"Withdrawals\" \"geometry\"   \n```\n:::\n\n```{.r .cell-code}\nnrow(philly_schools_sf_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 204\n```\n:::\n:::\n\nOnce joined, we dropped rows that did not have values in Attendance and Withdrawal. This resulted in 204 public schools and their metrics located in Philadelphia City Limits.\n\n###Tree density\nLocation of trees data was extracted from Opendata Philly. A Kernel Density Estimation was used to estimate the density of trees. The higher the value is, the more trees there will be in this (and surronding) cell\n\n::: {.cell}\n\n```{.r .cell-code}\ntree_path <- here(\"data\", \"ppr_tree_inventory_2024\")\n\ntree_shp_path <- file.path(tree_path, \"ppr_tree_inventory_2024.shp\")\n\n\ntrees=st_read(tree_shp_path)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nReading layer `ppr_tree_inventory_2024' from data source \n  `C:\\Users\\Tim Wen\\Documents\\GitHub\\portfolio-setup-wenshaoting6-ui\\data\\ppr_tree_inventory_2024\\ppr_tree_inventory_2024.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 151713 features and 6 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -8380434 ymin: 4847791 xmax: -8344373 ymax: 4885938\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n:::\n\n```{.r .cell-code}\ntrees=st_transform(trees,2272)\n\n# Convert sf points to spatstat ppp object\ncoords_trees <- st_coordinates(trees)\npp_trees <- ppp(x = coords_trees[,1], y = coords_trees[,2], window = win)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: 355 points were rejected as lying outside the specified window\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: data contain duplicated points\n```\n:::\n\n```{.r .cell-code}\n# ==== Run Kernel Density Estimation ====\n# Sigma = bandwidth in map units (here, meters)\ndensity_map_trees <- density.ppp(pp_trees, edge = TRUE, at = \"pixels\",eps = c(100, 100))\n\n# ==== Convert to raster ====\nr_trees <- rast(density_map_trees)\ncrs(r_trees) <- st_crs(philly_boundary)$proj4string\nr_trees <- mask(r_trees, vect(philly_boundary))  # mask to county boundary\n```\n:::\n\n\n### Joining data together\nFirst, since commercial and office POI and trees are point data, and the more they cluster the higher the housing price will be. As a result, we use Kernel Density method to estimate the density of them. Value of the cell was assign to the point (housing prices), if the point falls within it. \n\nSecond, as census tracts and neighborhood are polygon data, a st_within spatial join was used to join them with housing data. Values from polygon data will assign to the points when points fall within it.  \n\n::: {.cell}\n\n```{.r .cell-code}\n# Geometry - Cenus Data Merge\nphilly_tract_sf$GEOID=as.numeric(philly_tract_sf$GEOID)\nphilly_tract_map <- philly_tract_sf %>%\n  left_join(philly_censustract, by = \"GEOID\")\n\n#convert housing prices data into point data\nphl_sales_clean_sf = phl_sales_clean%>%\n  mutate(geometry = st_as_sfc(shape)) %>%   # parse WKT into geometry\n  st_as_sf(crs = 2272)  \n#convert and match the crs\nphilly_schools_sf_clean=philly_schools_sf_clean%>%\n  st_transform(2272)\nphilly_neighborhoods=philly_neighborhoods%>%\n  st_transform(2272)\nphilly_tract_map=philly_tract_map%>%\n  st_transform(2272)\n#merge them together\nphl_sales_clean_sf_final=phl_sales_clean_sf%>%\n  st_join(philly_tract_map,join=st_within)%>%\n  st_join(philly_neighborhoods,join = st_within)\nphl_sales_clean_sf_final <- st_transform(phl_sales_clean_sf_final, crs = st_crs(r_trees))\nphl_sales_clean_sf_final$EconKDE <- raster::extract(r_Economic,phl_sales_clean_sf_final)\nphl_sales_clean_sf_final$TreeKDE <- raster::extract(r_trees, phl_sales_clean_sf_final)  \nphl_sales_clean_sf_final=phl_sales_clean_sf_final%>%\n  st_transform(2272)\n```\n:::\n\n\n\n### Summary table before and after dimensions\n\n::: {.cell}\n\n```{.r .cell-code}\nbefore_after_summary <- data.frame(\n  Stage = c(\"Raw Data\", \n            \"After Residential Filter (2023–24)\", \n            \"After Removing Errors & NAs\", \n            \"After Spatial Joins & Final Cleaning\"),\n  Rows = c(nrow(phl_sales),\n           nrow(phl_sales_res_23_24),\n           nrow(phl_sales_clean),\n           nrow(phl_sales_clean_sf_final)),\n  Columns = c(ncol(phl_sales),\n              ncol(phl_sales_res_23_24),\n              ncol(phl_sales_clean),\n              ncol(phl_sales_clean_sf_final))\n)\n\nknitr::kable(before_after_summary, caption = \"Data dimensions before and after cleaning\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: 'xfun::attr()' is deprecated.\nUse 'xfun::attr2()' instead.\nSee help(\"Deprecated\")\n\nWarning: 'xfun::attr()' is deprecated.\nUse 'xfun::attr2()' instead.\nSee help(\"Deprecated\")\n```\n:::\n\n::: {.cell-output-display}\nTable: Data dimensions before and after cleaning\n\n|Stage                                |   Rows| Columns|\n|:------------------------------------|------:|-------:|\n|Raw Data                             | 583802|      79|\n|After Residential Filter (2023–24)   |  34628|      79|\n|After Removing Errors & NAs          |  22131|      81|\n|After Spatial Joins & Final Cleaning |  22131|     106|\n:::\n:::\n\n\n\n\n\n# PHASE 2: EXPLORATORY DATA ANALYSIS\n\n### Distribution of sale prices (histogram)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the median / mean to plot\nprice_median <- median(phl_sales_clean$sale_price, na.rm = TRUE)\n\nggplot(phl_sales_clean, aes(sale_price)) +\n  geom_histogram(bins = 60, fill = \"darkseagreen3\", color = \"black\") +\n  geom_vline(xintercept = price_median, linetype = 5) +\n  annotate(\"text\",\n           x = price_median, \n           y = 6300, \n           label = \"Median\",\n           hjust = -0.2, \n           color = \"black\", \n           size = 3) +\n  scale_x_continuous(labels = label_dollar()) +\n  labs(title = \"Distribution of Home Sale Prices\",\n       subtitle = \"For Philadelphia Residential Properties in 2023-2024\",\n       x = \"Sale Price\",\n       y = \"Count\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The histogram plot above shows the full distribution of home sale prices for residential properties in 2023-2024 from our cleaned dataset. The data is extremely right-skewed, highlighting a majority of prices under \\$500,000 with a long tail of more expensive homes thereafter. The main issue with the extreme outliers of home prices exceeding \\$5 million that make the visibility of this plot hard to interpret. Also, there are major gaps at higher sales prices as we see the data become more spread out, further indicating the presence of outliers. Therefore, to remedy this, we will plot a second histogram of the price distribution, excluding the top 5% of sales prices from the original cleaned dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create new df, filtering out the top 5% of house prices (outliers)\nprice_95_perc <- quantile(phl_sales_clean$sale_price, 0.95, na.rm = TRUE)\ndf_95_exclude <- filter(phl_sales_clean, sale_price <= price_95_perc)\n\n# Calculate the median / mean to plot from trimmed distribution\nprice_median_95_exc <- median(df_95_exclude$sale_price, na.rm = TRUE)\nprice_mean_95_exc <- mean(df_95_exclude$sale_price, na.rm = TRUE)\n\n\nggplot(df_95_exclude, aes(sale_price)) +\n  geom_histogram(bins = 20, fill = \"darkseagreen3\", color = \"black\") +\n  geom_vline(xintercept = price_mean_95_exc, linetype = 5) +\n  geom_vline(xintercept = price_median_95_exc, linetype = 5) +\n  annotate(\"text\",\n           x = price_mean_95_exc,\n           y = 2400,\n           label = \"Mean\", \n           hjust = - 0.1, \n           color = \"black\", \n           size = 3) +\n  annotate(\"text\",\n           x = price_median_95_exc, \n           y = 2450, \n           label = \"Median\",\n           hjust = 1.25, \n           color = \"black\", \n           size = 3) +\n  scale_x_continuous(labels = label_dollar()) +\n  labs(\n    title = \"Distribution of Home Sale Prices\",\n    subtitle = \"For Philadelphia Residential Properties in 2023-2024\",\n    caption = \"Histogram and median/mean statistics were computed on filtered sample (sale price ≤ 95th percentile) for better visibility.\",\n    x = \"Sale Price\",\n    y = \"Count\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\")\n  ) \n```\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** In this revised histogram, we get a much better sense of how the sales prices are distributed without the presence of extreme outliers. As we saw before, the data is definitely right-skewed since the median (\\$235,250) is less than the mean (\\$322,231) even when removing large outliers from the top 5% of the distribution. We can visualize that the standard housing market in Philadelphia from 2023-2024 ranges between \\$0 and \\$800,000. The distribution has a single peak around \\$200,000, indicating that it is unimodal with a typical (or most common) home sale price in the realm of \\$150,000 to \\$250,000. This is an indication that it may be best to omit these significant outliers from our dataset when building our model for home sale price prediction. The homes on the higher end of the sale price distribution are determined by a combination of structural features (such total livable area) and spatial features (such as nearby city centers) that drive up the prices of these homes. The goal of this study is to determine what features, both structural and spatial, are significant in predicting home sale prices in Philadelphia and create an accurate model to help policy makers in valuating property tax assessments.\n\n### Geographic distribution of sales price by tract\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tmap)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tmap' was built under R version 4.3.3\n```\n:::\n\n```{.r .cell-code}\nprice_95_perc <- quantile(phl_sales_clean$sale_price, 0.95, na.rm = TRUE)\ndf_95_exclude <- phl_sales_clean %>%\n  filter(sale_price <= price_95_perc)\n\ndf_95_exclude_sf <- df_95_exclude %>%\n  mutate(geometry = st_as_sfc(shape)) %>%\n  st_as_sf(crs = 2272) %>%\n  st_join(philly_tract_map, join = st_within)\n\ntract_price_summary <- df_95_exclude_sf %>%\n  st_drop_geometry() %>%\n  group_by(GEOID) %>%\n  summarize(median_price = median(sale_price, na.rm = TRUE))\n\nphilly_price_map <- philly_tract_map %>%\n  left_join(tract_price_summary, by = \"GEOID\")\n\ntmap_mode(\"plot\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nℹ tmap mode set to \"plot\".\n```\n:::\n\n```{.r .cell-code}\nprice_map <- tm_shape(philly_price_map) +\n  tm_polygons(\n    col = \"median_price\",\n    style = \"quantile\",\n    n = 5,\n    palette = \"YlGnBu\",\n    title = \"Median Sale Price (≤ 95th Percentile)\"\n  ) +\n  tm_layout(\n    main.title = \"Median Home Sale Prices by Census Tract (Filtered to ≤ 95th Percentile)\",\n    main.title.position = \"center\",\n    main.title.fontface = \"bold\",\n    outer.margins = c(0.10, 0.02, 0.02, 0.02),\n    legend.outside = TRUE\n  ) +\n  tm_shape(df_95_exclude_sf) +\n  tm_dots(\n    col = \"gray30\",\n    alpha = 0.3,\n    size = 0.02,\n    legend.show = FALSE\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\n── tmap v3 code detected ───────────────────────────────────────────────────────\n[v3->v4] `tm_polygons()`: instead of `style = \"quantile\"`, use fill.scale =\n`tm_scale_intervals()`.\nℹ Migrate the argument(s) 'style', 'n', 'palette' (rename to 'values') to\n  'tm_scale_intervals(<HERE>)'[v3->v4] `tm_polygons()`: use 'fill' for the fill color of polygons/symbols\n(instead of 'col'), and 'col' for the outlines (instead of 'border.col').[v3->v4] `tm_polygons()`: migrate the argument(s) related to the legend of the\nvisual variable `fill` namely 'title' to 'fill.legend = tm_legend(<HERE>)'[v3->v4] `tm_layout()`: use `tm_title()` instead of `tm_layout(main.title = )`[v3->v4] `tm_dots()`: use `fill_alpha` instead of `alpha`.[v3->v4] `tm_dots()`: use `fill.legend = tm_legend_hide()` instead of\n`legend.show = FALSE`.[tm_dots()] Argument `legend.show` unknown.\n```\n:::\n\n```{.r .cell-code}\nprice_map\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n[cols4all] color palettes: use palettes from the R package cols4all. Run\n`cols4all::c4a_gui()` to explore them. The old palette name \"YlGnBu\" is named\n\"brewer.yl_gn_bu\"\nMultiple palettes called \"yl_gn_bu\" found: \"brewer.yl_gn_bu\", \"matplotlib.yl_gn_bu\". The first one, \"brewer.yl_gn_bu\", is returned.\n\n[plot mode] fit legend/component: Some legend items or map compoments do not\nfit well, and are therefore rescaled.\nℹ Set the tmap option `component.autoscale = FALSE` to disable rescaling.\n```\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:**\n\nThis visualization shows clear spatial clustering of home prices in Philadelphia when looking at the typical market excluding outliers. Higher median prices are concentrated in Center City, University City, and select neighborhoods in South Philadelphia and Northwest Philadelphia. This supports our need to include additional predictors to account amenity density and economic activity.\n\n### Distribution of median income by neighborhood\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncensus_points <- st_centroid(philly_tract_map)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: st_centroid assumes attributes are constant over geometries\n```\n:::\n\n```{.r .cell-code}\npoints_joined <- st_join(census_points, philly_neighborhoods)\n\nmean_income_by_neighborhood <- points_joined %>%\n  st_drop_geometry() %>%\n  group_by(MAPNAME) %>%\n  summarise(mean_income = mean(median_income, na.rm = TRUE))\n\nphilly_neighborhood_income <- philly_neighborhoods %>%\n  left_join(mean_income_by_neighborhood, by = \"MAPNAME\")\n\nlibrary(tmap)\n\ntmap_mode(\"plot\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nℹ tmap mode set to \"plot\".\n```\n:::\n\n```{.r .cell-code}\nneighborhood_income_map <- tm_shape(philly_neighborhood_income) +\n  tm_polygons(\n    col = \"mean_income\",\n    style = \"quantile\",\n    n = 5,\n    palette = \"YlOrRd\",\n    title = \"Median Household Income\"\n  ) +\n  tm_layout(\n    main.title = \"Median Household Income by Neighborhood\",\n    main.title.position = \"center\",\n    outer.margins = c(0.10, 0.02, 0.02, 0.02),  # <-- more top padding\n    legend.outside = TRUE\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\n── tmap v3 code detected ───────────────────────────────────────────────────────\n[v3->v4] `tm_polygons()`: instead of `style = \"quantile\"`, use fill.scale =\n`tm_scale_intervals()`.\nℹ Migrate the argument(s) 'style', 'n', 'palette' (rename to 'values') to\n  'tm_scale_intervals(<HERE>)'[v3->v4] `tm_polygons()`: migrate the argument(s) related to the legend of the\nvisual variable `fill` namely 'title' to 'fill.legend = tm_legend(<HERE>)'[v3->v4] `tm_layout()`: use `tm_title()` instead of `tm_layout(main.title = )`\n```\n:::\n\n```{.r .cell-code}\nneighborhood_income_map\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n[cols4all] color palettes: use palettes from the R package cols4all. Run\n`cols4all::c4a_gui()` to explore them. The old palette name \"YlOrRd\" is named\n\"brewer.yl_or_rd\"\nMultiple palettes called \"yl_or_rd\" found: \"brewer.yl_or_rd\", \"matplotlib.yl_or_rd\". The first one, \"brewer.yl_or_rd\", is returned.\n\n[plot mode] fit legend/component: Some legend items or map compoments do not\nfit well, and are therefore rescaled.\nℹ Set the tmap option `component.autoscale = FALSE` to disable rescaling.\n```\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:**\n\nIn this visualization depicting median incomes of residents by neighborhoods, we observe continued spatial clustering of wealth indicators in areas like Center City, Northwest Philadelphia, and South Philadlephia. This is consistent with the basic aggregation of home sale prices on census tracts. The presence of high income in tandem with high housing cost serves as an indication of their relationship and justifies the use of economic predictors in our model. With this spatial auto-correlation, it is important that the model absorbs spatial variation by utilizing additional spatial features.   \n\n### Price vs. structural features\n\n#### 1. Number of Bathrooms\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(phl_sales_clean, aes(x = factor(number_of_bathrooms), y = sale_price)) +\n  geom_boxplot(fill = \"lightcyan2\", outlier.color = \"firebrick\", outlier.alpha = 0.2) +\n  scale_y_continuous(labels = scales::label_dollar()) +\n  labs(title = \"Distribution of Home Sale Prices by Number of Bathrooms\", \n       subtitle = \"For Philadelphia Residential Properties in 2023-2024\",\n       x = \"Bathrooms\", \n       y = \"Sale Price\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** Since number of bathrooms is a discrete variable, a scatter plot is not suitable to visualize this predictor's relationship with the target variable of sale price; therefore, we opted to use box plots instead. In this first plot, we see a distinct positive relationship between number of bathrooms and home sale price. Intuitively, this makes sense since homes with more bathrooms should on average sell at higher prices. Another trend is that there are more outliers in homes with less bathrooms (between 1 and 3). These outliers are likely due to external spatial factors such as neighborhoods. Housing prices tend to surge in highly desirable neighborhoods such as Rittenhouse Square, which explains the presence of many outliers plotted above the upper bound of these boxplots. Another trend is that variance of sale prices begins to significantly widen for homes with more than 3 bedrooms. This suggests that larger homes with more bathrooms experience more price dispersion relative to those with less bathrooms. Lastly, it is worth noting that there are very few observations of homes with 8 or 12 bathrooms, indicating that it would be beneficial to remove them from our dataset to better capture the true relationship between price and number of bathrooms.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(phl_sales_clean, aes(x = factor(number_of_bathrooms), y = log(sale_price))) +\n  geom_boxplot(fill = \"lightcyan2\", outlier.color = \"firebrick\", outlier.alpha = 0.2) +\n  scale_y_continuous(labels = scales::label_dollar()) +\n  labs(title = \"Distribution of Log(Home Sale Prices) by Number of Bathrooms\", \n       subtitle = \"For Philadelphia Residential Properties in 2023-2024\",\n       x = \"Bathrooms\", \n       y = \"Log(Sale Price)\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** In addition, we also plotted with the y-axis transformed to the log of sales price. We notice that there is still a positive relationship that appears more linear than the first plot. The log transformation helps reduce the effect of extreme outliers by compressing the distribution of house sale prices. This transformation also serves to center the distributions as noted by the presence of both positive and negative outliers. These benefits suggest that log-transforming our target variable for a linear regression is the best suitable method to yield an accurate model. \n\n#### 2. Number of Bedrooms\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(phl_sales_clean, aes(x = factor(number_of_bedrooms), y = sale_price)) +\n  geom_boxplot(fill = \"lightcyan2\", outlier.color = \"firebrick\", outlier.alpha = 0.2) +\n  scale_y_continuous(labels = scales::label_dollar()) +\n  labs(title = \"Distribution of Home Sale Prices by Number of Bedrooms\", \n       subtitle = \"For Philadelphia Residential Properties in 2023-2024\",\n       x = \"Bedrooms\", \n       y = \"Sale Price\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The above plot to measure the relationship between home sale price and number of bedrooms is positive, indicating that homes with more bedrooms tend to sell at higher prices. However, this relationship looks significantly less strong than the relationship between sale price and number of bathrooms. We observe many outliers across homes with various bedroom sizes, most notably those with 2 - 5 bedrooms. The intuition is that these size households are more likely to be sold on the market with higher variability in sales prices, particularly in the upper tail, demonstrating right-skew. These high outliers represent luxury properties that sell for abnormally high sale prices due to other external variables like neighborhood, size etc. Again, we have a small number of very large homes with 10, 11, and 12 bedrooms that are candidates for removal before building our model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(phl_sales_clean, aes(x = factor(number_of_bedrooms), y = log(sale_price))) +\n  geom_boxplot(fill = \"lightcyan2\", outlier.color = \"firebrick\", outlier.alpha = 0.2) +\n  scale_y_continuous(labels = scales::label_dollar()) +\n  labs(title = \"Distribution of Log(Home Sale Prices) by Number of Bedrooms\", \n       subtitle = \"For Philadelphia Residential Properties in 2023-2024\",\n       x = \"Bedrooms\", \n       y = \"Log(Sale Price)\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** As before, we can log-transform the target variable log(sale price) to better visualize the relationship with number of bedrooms. We still see a positive relationship that appears more linear than in our earlier plot. As before, the log-transformation stabilizes the variance to mitigate outliers and centers the data demonstrated by outliers at both the upper and lower tails. The strength of the relationship still appears to be not as obvious as with the number of bathrooms. In other words, number of bathrooms may be a more suitable predictor of sale price from these EDA observations. To avoid the risk of multicollinearity, we will keep this finding in mind when determining what structural features should be included in our final model.\n\n#### 3. Total Livable Area\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(phl_sales_clean, aes(x = total_livable_area, sale_price)) +\n  geom_point(alpha = 0.1, size = 1) +\n  geom_smooth(method = \"lm\", se = FALSE, linetype = 5, color = \"firebrick\") +\n  scale_y_continuous(labels = label_dollar()) +\n  labs(title = \"Distribution of Home Sale Prices by Total Livable Area\", \n       subtitle = \"For Philadelphia Residential Properties in 2023-2024\",\n       x = \"Total Livable Area\", \n       y = \"Sale Price\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The plot represents the relationship between the non-transformed target sale price and predictor total livable area. We can see that the relationship to be positive with evidence of heavy right-skew with the majority of data points clustered in the bottom-left with less than 3000 sq ft of area and \\$500,000 price. Also, we notice that although the relationship is positive, it does not appear to be linear, a violation of a crucial assumption in linear regression. As before, there is the presence of luxury homes as large outliers that can pull the regression line upward, which would create biased estimates on model coefficients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(phl_sales_clean, aes(x = log(total_livable_area), log(sale_price))) +\n  geom_point(alpha = 0.075, size = 1) +\n  geom_smooth(method = \"lm\", se = FALSE, linetype = 5, color = \"firebrick\") +\n  scale_y_continuous(labels = label_dollar()) +\n  labs(title = \"Distribution of Log(Home Sale Prices) by Total Livable Area\", \n       subtitle = \"For Philadelphia Residential Properties in 2023-2024\",\n       x = \"Log(Total Livable Area)\", \n       y = \"Log(Sale Price)\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** By log-transforming both sale price and total livable area, we visualize a relationship that appears much more linear. As we saw before, there seem to be more variability in homes with smaller areas that are more common in this dataset. The transformation has more of a uniform, symmetric spread of points above and below the regression line. We can interpret this relationship as increasing the percentage of total livable area will lead to some constant increase in the percentage of sale price with this transformation. We should keep at mind that the non-constant variance is alarming for potential heteroskedasticity in our model. Again, through the log-transformation of our target variable, we observe a more linear relationship, strengthening the notion for the need for this transformation in our modeling phase.\n\n#### 4. Age (Sale Date - Year Built)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(phl_sales_clean, aes(x = age, y = sale_price)) +\n  geom_point(alpha = 0.076, size = 1) +\n  scale_y_continuous(labels = label_dollar()) +\n  labs(title = \"Distribution of Home Sale Prices by Age\", \n       subtitle = \"For Philadelphia Residential Properties in 2023-2024\",\n       x = \"Age\", \n       y = \"Sale Price\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** In the above plot, it does not reveal any significant relationship between sale price and home age. The main issue is that most of the data is clustered at the bottom of the figure at low sale prices regardless of age. There are some noticeable outliers along with increased variability for middle-aged homes around 75 to 125 years old. In general, it seems that there newer homes (lower age) demonstrate somewhat higher price levels on average. However, from this plot alone, it is difficult to verify.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(phl_sales_clean, aes(x = age, log(sale_price))) +\n  geom_point(alpha = 0.075, size = 1) +\n  geom_smooth(method = \"loess\", span = 0.75, se = FALSE, color = \"firebrick\") +\n  scale_y_continuous(labels = label_dollar()) +\n  labs(title = \"Distribution of Log(Home Sale Prices) by Age\", \n       subtitle = \"For Philadelphia Residential Properties in 2023-2024\",\n       x = \"Age\", \n       y = \"Log(Sale Price)\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** After doing the trick to log-transform sale price, we see an interesting shape that somewhat resembles a crucial theory we learned in lecture. This theory outlines that Age has a U-shaped effect on price. Newer homes are sought after due to recent construction with more modern amenities, whereas very old homes are considered to have historic value or charm. The middle-aged homes are therefore the least desirable homes that likely are not modernized with significant wear and tear without the allure of a historic home. While this theory makes sense, it somewhat breaks down for these middle aged homes as their sale prices experience much more variability, which would make our model more at risk of heteroskedasticity. This is likely due to a majority of samples in our dataset within this range whose sale price cannot be explained by age alone. Therefore, it is wise to proceed with caution with using the age variable in building our predictive model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_age_groups <- phl_sales_clean |>\n  mutate(\n    age_group = case_when(\n      age < 20 ~ \"New (<20 years)\",\n      age < 80 ~ \"Middle (20–80 years)\",\n      age >= 80 ~ \"Historic (>80 years)\"\n    ),\n    age_group = factor(age_group, levels = c(\"New (<20 years)\", \"Middle (20–80 years)\", \"Historic (>80 years)\"))\n  )\n\nggplot(df_age_groups, aes(age_group, log(sale_price))) +\n  geom_boxplot(fill = \"lightcyan2\", outlier.colour = \"firebrick\", outlier.alpha = 0.2) +\n  labs(\n    title = \"Distribution of Log(Sale Price) by Age Group\",\n    subtitle = \"Philadelphia Residential Sales in 2023–2024\",\n    x = \"Age Group\", y = \"log(Sale Price)\",\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** When we engineer a new age group feature, the U-shaped distribution does not appear to be valid in the case of our dataset. Using the age segmentations defined in class, it now appears as there is an inverse (negative) relationship between log(sale price) and age group, not a U-shape distribution. One hypothesis is that very old buildings in Philadelphia are too worn down or don't hold enough historic value to counteract its age. Whatever the reason may be, it seems that engineering a feature for age group is preferred over using age directly and to expect increasing age to a home to depreciate its value over time.\n\n### Price vs. spatial features\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(phl_sales_clean_sf_final, aes(x = EconKDE$lyr.1, y=sale_price)) +\n  geom_point(alpha = 0.1, size = 1) +\n  geom_smooth(method = \"lm\", se = FALSE, linetype = 5, color = \"firebrick\") +\n  scale_y_continuous(labels = label_dollar()) +\n  labs(title = \"Distribution of Home Sale Prices by Economic KDE Value\", \n       subtitle = \"For Philadelphia Residential Properties in 2023-2024\",\n       x = \"KDE\", \n       y = \"Sale Price\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 3 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 3 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:**\nThe plot represents the relationship between the non-transformed target sale price and predictor KDE for economic activities. We can see that the relationship to be positive with evidence of heavy right-skew with the majority of data points clustered in the bottom-left with less than a KDE value of 0.000075 and \\$500,000 price. Also, we notice that although the relationship is positive, it does not appear to be linear, a violation of a crucial assumption in linear regression. It seems that the trend increases first till about 0.00008 and then decreases. As before, there is the presence of some homes as large outliers that can pull the regression line upward, which would create biased estimates on model coefficients.\n\n### One creative visualization: Sale Price Distribution Across City\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#join sales data with neighborhood data\nphilly_sales_neigh <- st_join(philly_neighborhoods, phl_sales_clean_sf_final, join = st_contains)\n\n# Summarize count of sales per neighborhood\nphilly_sales_count <- philly_sales_neigh %>%\n  group_by(NAME) %>%\n  summarize(\n    sales_count = n(),\n    .groups = \"drop\"\n  )\n\n# Plot\nggplot(philly_sales_count) +\n  geom_sf(aes(fill = sales_count), color = \"white\", size = 0.3) +\n  scale_fill_viridis_c(\n    option = \"inferno\",\n    direction = -1,\n    name = \"Number of Sales\",\n    trans = \"sqrt\"  \n  ) +\n  labs(\n    title = \"Number of Sales by Neighborhood (2023–2024)\",\n    subtitle = \"Philadelphia County\"\n  ) +\n  theme_void(base_size = 14) +\n  theme(\n    plot.title = element_text(face = \"bold\", hjust = 0.5),\n    plot.subtitle = element_text(hjust = 0.5),\n    legend.position = \"right\",\n    legend.key.height = unit(1.2, \"cm\")\n  )\n```\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:**\nBased on the map the number of sales is not evenly distributed across neighborhoods in Philadelphia County. Some of the neighborhoods in the east/northeast have a significant large number of home sales while the number of that in the south is lower. Moreover, the Center City area seems to also have a smaller number of sales compared to others, highly due to fewer number of housing units.\n\n\n# PHASE 3: FEATURE ENGINEERING\n\n### Final Data Cleaning from Structural EDA\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 99th percentile of sales prices to remove\nprice_99_perc <- quantile(phl_sales_clean$sale_price, 0.99, na.rm = TRUE)\n\n# Relevant columns to keep for modeling\nrel_columns <- c(\n    # Location / Shape\n    \"census_tract\", \"shape\", \"location\", \"zip_code\",\n    # Target\n    \"sale_price\", \"log_price\",\n    # Regressors (and potential ones)\n    \"total_livable_area\", \"log_total_livable_area\",\n    \"number_of_bedrooms\", \"number_of_bathrooms\",\n    \"year_built\", \"age\", \"age_group\",\n    \"interior_condition\", \"quality_grade\" \n  )\n\nphl_sales_final <- phl_sales_clean |>\n  filter(\n    # Remove top 1% of sale price (extreme outliers)\n    # This creates an upper bound of around $2 million rather than $6 million to further reduce outlier effects in modeling\n    sale_price < price_99_perc,\n    # Remove bathrooms > 7\n    number_of_bathrooms < 8,\n    # Remove bedrooms > 9\n    number_of_bedrooms < 10\n  )|>\n  mutate(\n    # Log of sale price\n    log_price = log(sale_price),\n    # Log of total livable area\n    log_total_livable_area = log(total_livable_area),\n    # Age group buckets (new, middle_age, historic)\n    age_group = case_when(\n      age < 20 ~ \"New (<20)\",\n      age <= 80 ~ \"Middle (20–80)\",\n      age > 80 ~ \"Historic (>80)\"\n    ),\n    # For modeling as dummy variables\n    age_group = factor(age_group, levels = c(\"New (<20)\", \"Middle (20–80)\", \"Historic (>80)\"))\n  ) |>\n  # Select relevant columns\n  select(any_of(rel_columns))\n\n\n#convert housing prices data into point data\nphl_sales_final_sf = phl_sales_final%>%\n  mutate(geometry = st_as_sfc(shape)) %>%   # parse WKT into geometry\n  st_as_sf(crs = 2272)  \n#convert and match the crs\nphilly_schools_sf_final=philly_schools_sf_clean%>%\n  st_transform(2272)\nphilly_neighborhoods=philly_neighborhoods%>%\n  st_transform(2272)\nphilly_tract_map=philly_tract_map%>%\n  st_transform(2272)\n#merge them together\nphl_sales_final_sf_final=phl_sales_final_sf%>%\n  st_join(philly_tract_map,join=st_within)%>%\n  st_join(philly_neighborhoods,join = st_within)\nphl_sales_final_sf_final <- st_transform(phl_sales_final_sf_final, crs = st_crs(r_trees))\nphl_sales_final_sf_final$EconKDE <- raster::extract(r_Economic,phl_sales_final_sf_final)\nphl_sales_final_sf_final$TreeKDE <- raster::extract(r_trees, phl_sales_final_sf_final)  \nphl_sales_final_sf_final=phl_sales_final_sf_final%>%\n  st_transform(2272)\n```\n:::\n\n\n\n### Classifying Neighborhood\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#convert census tract into points\ncensus_points=st_centroid(philly_tract_map)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: st_centroid assumes attributes are constant over geometries\n```\n:::\n\n```{.r .cell-code}\npoints_joined <- st_join(census_points, philly_neighborhoods)\n\n# Calculate mean MHI for each polygon\nmean_mhi_by_poly <- points_joined %>%\n  st_drop_geometry() %>%             \n  group_by(MAPNAME) %>%            \n  summarise(meanMHI = mean(median_income, na.rm = TRUE))\n\n# Join the result back to the polygon layer\nphl_sales_final_sf_final <- phl_sales_final_sf_final %>%\n  left_join(mean_mhi_by_poly, by = \"MAPNAME\")%>%\n  st_as_sf() \n# reclassify the neighborhood data based on quantile (25%)\nphl_sales_final_sf_final$MHI_quantile <- cut(\n  phl_sales_final_sf_final$meanMHI,\n  breaks = quantile(\n    phl_sales_final_sf_final$meanMHI,\n    probs = seq(0, 1, 0.25),   \n    na.rm = TRUE\n  ),\n  include.lowest = TRUE,\n  labels = c(\"Q1 (lowest)\", \"Q2\", \"Q3\", \"Q4 (highest)\")\n)\n```\n:::\n\n\n### Calculating distance to schools using K-nearest method\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute distance matrix\ndist_matrix <- st_distance(phl_sales_final_sf_final, philly_schools_sf_final)\n\n# Extract the 3 smallest distances for each point\nnearest_3 <- apply(dist_matrix, 1, function(x) sort(x)[1:3])\n\n# Get the average or total distance if needed\nmean_nearest3 <- apply(dist_matrix, 1, function(x) mean(sort(x)[1:3]))\n\nphl_sales_final_sf_final$mean_3nn_dist <- mean_nearest3\n```\n:::\n\n\n\n### Summary table\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#reformat raster data into a \"readable\" format by stargazer\nphl_sales_final_sf_final <- phl_sales_final_sf_final %>%\n  mutate(EconKDE = EconKDE$lyr.1,\n         TreeKDE = TreeKDE$lyr.1) \n\n#exclude the unnecessary data\nsummary_data <- phl_sales_final_sf_final %>%\n  st_drop_geometry() %>%\n  select(-c(\n    census_tract, shape, NAME.x, NAME.y, MAPNAME,\n    Shape_Area, Shape_Leng, location, zip_code, GEOID, \n    variabl, age_group, quality_grade, LISTNAME, MHI_quantile,\n    estimat,moe,pct_bch,pct_vcn,pct_wht,mdn_ncm,fmly_hh,totl_hh\n  ))\n\n# Keep only numeric columns\nsummary_numeric <- summary_data %>%\n  select(where(is.numeric))\nsummary_numeric_df <- as.data.frame(summary_numeric)\n\n# Print as txt in R\nstargazer(summary_numeric_df,\n          type = \"text\",\n          title = \"Summary Statistics\",\n          digits = 2,\n          summary.stat = c(\"n\", \"mean\", \"sd\", \"min\", \"median\", \"max\"),\n          covariate.labels = c(\"Sale Price\", \"Log Price\", \"Total Livable Area\", \n                            \"Log Total Livable Area\", \"Bedrooms\", \"Bathrooms\", \n                            \"Year Built\", \"Age\", \"Interior Condition\", \n                            \"Median Income\",\"Family HH\", \n                            \"Total HH\", \"% Bachelors\", \"% Vacant\", \"% White\",\n                            \"Econ KDE\", \"Tree KDE\", \"Mean MHI\", \n                            \"Mean 3 closest School Dist\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nSummary Statistics\n======================================================================================\nStatistic                    N       Mean     St. Dev.     Min     Median      Max    \n--------------------------------------------------------------------------------------\nSale Price                 21,904 290,409.00 247,036.10  10,000    235,000  2,285,000 \nLog Price                  21,904   12.29       0.81      9.21      12.37     14.64   \nTotal Livable Area         21,904  1,365.48    537.62      434      1,216     9,038   \nLog Total Livable Area     21,904    7.16       0.31      6.07      7.10       9.11   \nBedrooms                   21,904    3.08       0.71        0         3         9     \nBathrooms                  21,904    1.43       0.68        1         1         7     \nYear Built                 21,904  1,937.34    29.94      1,750     1,925     2,025   \nAge                        21,904   86.16      29.94       -2        98        274    \nInterior Condition         21,903    3.42       0.90        1         4         7     \nMedian Income              21,644 66,519.72  30,635.44   13,721    60,957    192,727  \nFamily HH                  21,902  1,096.04    435.24       0       1,054     2,484   \nTotal HH                   21,902  1,946.09    603.64       0       1,911     3,713   \n% Bachelors                21,899   32.43      22.74      1.50      26.41     94.84   \n% Vacant                   21,897    9.32       5.94      0.00      8.15      32.88   \n% White                    21,899   38.19      29.95      0.00      35.22     95.51   \nEcon KDE                   21,901   0.0000     0.0000     0.00     0.0000     0.0000  \nTree KDE                   21,901   0.0000     0.0000    0.0000    0.0000     0.0001  \nMean MHI                   21,551 66,655.66  27,951.74  18,646.00 59,779.14 168,021.00\nMean 3 closest School Dist 21,902  2,601.60   1,193.24   336.99   2,365.72  11,109.39 \n--------------------------------------------------------------------------------------\n```\n:::\n:::\n\n### Final Cleaning Before Building the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor_model_building <- phl_sales_final_sf_final %>%\n  st_drop_geometry() %>%\n  select(-c(\n    census_tract, shape, NAME.x, NAME.y,\n    Shape_Area, Shape_Leng, location, zip_code, GEOID, \n    variabl, LISTNAME, \n    estimat,moe,pct_bch,pct_vcn,pct_wht,mdn_ncm,fmly_hh,totl_hh\n  ))\n```\n:::\n\n\n\n\n### Justification of feature engineered variables\nWe have used a number of methods to create spatial features in both Phase 1 and 3. First, in Phase 1, since commercial and office POI and trees are point data, and the more they cluster the higher the housing price will be. As a result, we use Kernel Density method to estimate the density of them. Value of the cell was assign to the point (housing prices), if the point falls within it. \n\nSecond, as census tracts and neighborhood are polygon data, a st_within spatial join was used to join them with housing data. Values from polygon data will assign to the points when points fall within it. \n\nThird, as there are too many neighborhoods, it is hard to interpret the coefficient of them as it is a categorical variable. We reclassify it with four different categories based on quantile of MHI(25%). To calculate the MHI each neighborhood, we first take the centroid of each census tract and summarize them within each neighborhood. Then we take the mean of MHI of the tracts that fall within the neighborhood.  \n\nLastly, different from poi and trees, a high cluster of schools may not reflect a high housing price. As a result, instead of using density estimation, we use 3-nearest distance and take the mean to capture some of the closest schools.\n\n\n# PHASE 4: Model Building\n\n### create train/test data first (make workflow smoother)\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nn <- nrow(for_model_building)\n\n# 70% training, 30% testing\ntrain_indices <- sample(1:n, size = 0.7 * n)\ntrain_data <- for_model_building[train_indices, ]\ntest_data <- for_model_building[-train_indices, ]\n```\n:::\n\n\n### Building the model progressively\n#### Model 1: Individual characteristic only\n\n::: {.cell}\n\n```{.r .cell-code}\n#run regression based on houses own characteristic\noptions(scipen = 999)\n\nmodel1=lm(log_price~log_total_livable_area+number_of_bedrooms+number_of_bathrooms+age\n          +interior_condition+quality_grade,data=for_model_building)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_price ~ log_total_livable_area + number_of_bedrooms + \n    number_of_bathrooms + age + interior_condition + quality_grade, \n    data = for_model_building)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.9577 -0.3049  0.0787  0.3891  3.4380 \n\nCoefficients:\n                        Estimate Std. Error t value             Pr(>|t|)    \n(Intercept)             6.529298   0.212693  30.698 < 0.0000000000000002 ***\nlog_total_livable_area  0.980300   0.022853  42.895 < 0.0000000000000002 ***\nnumber_of_bedrooms     -0.160718   0.008096 -19.853 < 0.0000000000000002 ***\nnumber_of_bathrooms     0.266366   0.008810  30.234 < 0.0000000000000002 ***\nage                    -0.002154   0.000170 -12.669 < 0.0000000000000002 ***\ninterior_condition     -0.200855   0.005656 -35.513 < 0.0000000000000002 ***\nquality_grade5         -0.544895   0.470346  -1.158              0.24667    \nquality_gradeA         -0.130839   0.174874  -0.748              0.45436    \nquality_gradeA-        -0.099262   0.181311  -0.547              0.58406    \nquality_gradeA+        -0.098146   0.211833  -0.463              0.64314    \nquality_gradeB         -0.086036   0.152187  -0.565              0.57185    \nquality_gradeB-        -0.030713   0.151364  -0.203              0.83921    \nquality_gradeB+        -0.143282   0.157050  -0.912              0.36161    \nquality_gradeC         -0.311449   0.149543  -2.083              0.03729 *  \nquality_gradeC-        -0.265187   0.151489  -1.751              0.08004 .  \nquality_gradeC+        -0.190983   0.149772  -1.275              0.20227    \nquality_gradeD         -0.012507   0.156937  -0.080              0.93648    \nquality_gradeD-        -0.393465   0.319474  -1.232              0.21811    \nquality_gradeD+         0.058609   0.181214   0.323              0.74638    \nquality_gradeE         -0.608213   0.214061  -2.841              0.00450 ** \nquality_gradeE-        -0.844550   0.249411  -3.386              0.00071 ***\nquality_gradeE+        -0.539446   0.249377  -2.163              0.03054 *  \nquality_gradeS         -0.000180   0.470706   0.000              0.99969    \nquality_gradeX-         0.231081   0.471922   0.490              0.62438    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.631 on 21320 degrees of freedom\n  (560 observations deleted due to missingness)\nMultiple R-squared:  0.3762,\tAdjusted R-squared:  0.3755 \nF-statistic:   559 on 23 and 21320 DF,  p-value: < 0.00000000000000022\n```\n:::\n\n```{.r .cell-code}\n#check colinearity\nvif(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                           GVIF Df GVIF^(1/(2*Df))\nlog_total_livable_area 2.575150  1        1.604727\nnumber_of_bedrooms     1.758584  1        1.326116\nnumber_of_bathrooms    1.746226  1        1.321449\nage                    1.136640  1        1.066133\ninterior_condition     1.168964  1        1.081186\nquality_grade          1.618759 18        1.013469\n```\n:::\n\n```{.r .cell-code}\n#vif looks fine, check heteroskedasticity\n\nbptest(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  model1\nBP = 918.58, df = 23, p-value < 0.00000000000000022\n```\n:::\n\n```{.r .cell-code}\n#p-value is way too small, implying more variables may be needed (make sense)\n\n#calculate the RMSE\nmodel_train_1 <- lm(log_price~log_total_livable_area+number_of_bedrooms+number_of_bathrooms+age+interior_condition+quality_grade,data = train_data)\ntest_predictions_1 <- predict(model_train_1, newdata = test_data)\nrmse_test_1 <- sqrt(mean((test_data$log_price - test_predictions_1)^2,na.rm = TRUE))\nrmse_train_1 <- summary(model_train_1)$sigma\n\n\nplot(model1)\n```\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-41-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-41-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-41-4.png){width=672}\n:::\n:::\n\nIn residual plot, more observations are clustered when fitted value is lower, indicating bad distribution of residuals and nonlinearity. \n\nSame issue is reflected in Q-Q plot as well, the unlinearity revels the distribution of residual is not normal.\n\nThere is also heteroskedasticity, as the scale location shows, the line is not linear at all. \n\nThe outliers seems to have small influence on the leverage,as the line is almost linear shown in the last graph\n\n\n\n#### Model 2: add census variables into regression\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen = 999)\n\nmodel2=lm(log_price~log_total_livable_area+number_of_bedrooms+number_of_bathrooms+age\n          +interior_condition+median_income+I(family_hh/total_hh)\n          +pct_bachelors+pct_vacant+pct_white+quality_grade ,data=for_model_building)\n\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_price ~ log_total_livable_area + number_of_bedrooms + \n    number_of_bathrooms + age + interior_condition + median_income + \n    I(family_hh/total_hh) + pct_bachelors + pct_vacant + pct_white + \n    quality_grade, data = for_model_building)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.0860 -0.1929  0.0602  0.2645  3.4785 \n\nCoefficients:\n                            Estimate    Std. Error t value             Pr(>|t|)\n(Intercept)             8.3421163957  0.1726095234  48.329 < 0.0000000000000002\nlog_total_livable_area  0.5471578867  0.0187171204  29.233 < 0.0000000000000002\nnumber_of_bedrooms     -0.0000930605  0.0066451065  -0.014              0.98883\nnumber_of_bathrooms     0.1658833019  0.0071136170  23.319 < 0.0000000000000002\nage                    -0.0017382057  0.0001450935 -11.980 < 0.0000000000000002\ninterior_condition     -0.1788522839  0.0046035694 -38.851 < 0.0000000000000002\nmedian_income           0.0000006646  0.0000002539   2.617              0.00887\nI(family_hh/total_hh)   0.1350950371  0.0351207309   3.847              0.00012\npct_bachelors           0.0100245679  0.0003712951  26.999 < 0.0000000000000002\npct_vacant             -0.0162146228  0.0006761690 -23.980 < 0.0000000000000002\npct_white               0.0059899496  0.0001895432  31.602 < 0.0000000000000002\nquality_grade5         -0.2584774312  0.3731983101  -0.693              0.48857\nquality_gradeA         -0.0253911801  0.1389148859  -0.183              0.85497\nquality_gradeA-        -0.0413833230  0.1440207501  -0.287              0.77385\nquality_gradeA+        -0.0188415532  0.1682720604  -0.112              0.91085\nquality_gradeB         -0.0028989397  0.1209477204  -0.024              0.98088\nquality_gradeB-         0.0517136299  0.1203527567   0.430              0.66743\nquality_gradeB+        -0.0543410072  0.1247681362  -0.436              0.66318\nquality_gradeC          0.0299865474  0.1190752206   0.252              0.80118\nquality_gradeC-        -0.0004196752  0.1205682508  -0.003              0.99722\nquality_gradeC+         0.0535270619  0.1192110503   0.449              0.65343\nquality_gradeD          0.0619221140  0.1249970862   0.495              0.62033\nquality_gradeD-        -0.2241562239  0.2536336196  -0.884              0.37683\nquality_gradeD+         0.2617260493  0.1440708043   1.817              0.06929\nquality_gradeE         -0.2221555722  0.1699700561  -1.307              0.19122\nquality_gradeE-         0.0006583794  0.2133217806   0.003              0.99754\nquality_gradeE+        -0.1414838990  0.1980801341  -0.714              0.47506\nquality_gradeS          0.3174138047  0.3735475236   0.850              0.39549\nquality_gradeX-        -0.0726067390  0.3747667117  -0.194              0.84638\n                          \n(Intercept)            ***\nlog_total_livable_area ***\nnumber_of_bedrooms        \nnumber_of_bathrooms    ***\nage                    ***\ninterior_condition     ***\nmedian_income          ** \nI(family_hh/total_hh)  ***\npct_bachelors          ***\npct_vacant             ***\npct_white              ***\nquality_grade5            \nquality_gradeA            \nquality_gradeA-           \nquality_gradeA+           \nquality_gradeB            \nquality_gradeB-           \nquality_gradeB+           \nquality_gradeC            \nquality_gradeC-           \nquality_gradeC+           \nquality_gradeD            \nquality_gradeD-           \nquality_gradeD+        .  \nquality_gradeE            \nquality_gradeE-           \nquality_gradeE+           \nquality_gradeS            \nquality_gradeX-           \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.5006 on 21057 degrees of freedom\n  (818 observations deleted due to missingness)\nMultiple R-squared:  0.6046,\tAdjusted R-squared:  0.6041 \nF-statistic:  1150 on 28 and 21057 DF,  p-value: < 0.00000000000000022\n```\n:::\n\n```{.r .cell-code}\n#number of bedroom becomes statistical insignificant after controling census variable\n\n#check colinearity\nvif(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                           GVIF Df GVIF^(1/(2*Df))\nlog_total_livable_area 2.716497  1        1.648180\nnumber_of_bedrooms     1.861029  1        1.364195\nnumber_of_bathrooms    1.792325  1        1.338778\nage                    1.310400  1        1.144727\ninterior_condition     1.211476  1        1.100671\nmedian_income          5.065782  1        2.250729\nI(family_hh/total_hh)  1.906882  1        1.380899\npct_bachelors          5.971505  1        2.443666\npct_vacant             1.355322  1        1.164183\npct_white              2.696554  1        1.642119\nquality_grade          1.767306 18        1.015944\n```\n:::\n\n```{.r .cell-code}\n#edu_attainment and mhi may have muticolinearity\n\nbptest(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  model2\nBP = 1101.9, df = 28, p-value < 0.00000000000000022\n```\n:::\n\n```{.r .cell-code}\n#p-value is way too small, implying more variables may be needed (make sense)\n\n#calculate the RMSE\nmodel_train_2 <- lm(log_price~log_total_livable_area+number_of_bedrooms\n                    +number_of_bathrooms+age+interior_condition+median_income\n                    +I(family_hh/total_hh)\n                    +pct_bachelors+pct_vacant+pct_white\n                    +quality_grade,data = train_data)\ntest_predictions_2 <- predict(model_train_2, newdata = test_data)\nrmse_test_2 <- sqrt(mean((test_data$log_price - test_predictions_2)^2,na.rm = TRUE))\nrmse_train_2 <- summary(model_train_2)$sigma\n\n\n\nplot(model2)\n```\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-42-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-42-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-42-4.png){width=672}\n:::\n:::\n\nThe residual plot for model 2 looks much better than that in model 1. The number of observations are clustered when fitted value is lower decreases, indicating better distribution of residuals. The non-linearity issue also gets better\n\nQ-Q plot still does not look good, especially for the outliers. It seems that outliers is influencing the normality of residuals\n\nThere is also heteroskedasticity, as the scale location shows, the line is not linear at all. \n\nThe outlier seems to have small influence on the leverage,as the line is almost linear shown in the last graph\n\n#### Model 3: add spatial variables into regression\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen = 999)\n\nmodel3=lm(log_price~log_total_livable_area+number_of_bedrooms+number_of_bathrooms+age\n          +interior_condition+median_income+I(family_hh/total_hh)\n          +pct_bachelors+pct_vacant+pct_white+EconKDE+I(EconKDE^2)+TreeKDE\n          +mean_3nn_dist+quality_grade,data=for_model_building)\n\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_price ~ log_total_livable_area + number_of_bedrooms + \n    number_of_bathrooms + age + interior_condition + median_income + \n    I(family_hh/total_hh) + pct_bachelors + pct_vacant + pct_white + \n    EconKDE + I(EconKDE^2) + TreeKDE + mean_3nn_dist + quality_grade, \n    data = for_model_building)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.1057 -0.1942  0.0596  0.2625  3.4990 \n\nCoefficients:\n                                   Estimate           Std. Error t value\n(Intercept)                    8.6036566075         0.1739409030  49.463\nlog_total_livable_area         0.5292145525         0.0187197105  28.270\nnumber_of_bedrooms            -0.0009109252         0.0066423207  -0.137\nnumber_of_bathrooms            0.1630566046         0.0071009518  22.963\nage                           -0.0016927646         0.0001520806 -11.131\ninterior_condition            -0.1840812036         0.0046249286 -39.802\nmedian_income                  0.0000010105         0.0000002564   3.941\nI(family_hh/total_hh)          0.0303372010         0.0369350779   0.821\npct_bachelors                  0.0115934423         0.0004225493  27.437\npct_vacant                    -0.0131073182         0.0007620041 -17.201\npct_white                      0.0050131364         0.0002083044  24.066\nEconKDE                   -16495.2399181404      2410.3994780791  -6.843\nI(EconKDE^2)           726249580.0208528042  84616748.3888884783   8.583\nTreeKDE                    -2072.2939198252       378.8529681533  -5.470\nmean_3nn_dist                  0.0000009973         0.0000037327   0.267\nquality_grade5                -0.2801937457         0.3719047241  -0.753\nquality_gradeA                -0.0315975302         0.1383847119  -0.228\nquality_gradeA-               -0.0217700741         0.1434865993  -0.152\nquality_gradeA+               -0.0190744409         0.1676524137  -0.114\nquality_gradeB                 0.0052652689         0.1204892846   0.044\nquality_gradeB-                0.0613721062         0.1198940360   0.512\nquality_gradeB+               -0.0314875331         0.1243078747  -0.253\nquality_gradeC                 0.0380415396         0.1186273034   0.321\nquality_gradeC-                0.0043953616         0.1201299838   0.037\nquality_gradeC+                0.0608835976         0.1187565971   0.513\nquality_gradeD                 0.0818344068         0.1245513826   0.657\nquality_gradeD-               -0.2120033744         0.2526710870  -0.839\nquality_gradeD+                0.2654076464         0.1435263793   1.849\nquality_gradeE                -0.1888525792         0.1693689767  -1.115\nquality_gradeE-                0.0324770158         0.2125498392   0.153\nquality_gradeE+               -0.1153567286         0.1973507781  -0.585\nquality_gradeS                 0.3512498528         0.3721669235   0.944\nquality_gradeX-               -0.1145468118         0.3735303161  -0.307\n                                   Pr(>|t|)    \n(Intercept)            < 0.0000000000000002 ***\nlog_total_livable_area < 0.0000000000000002 ***\nnumber_of_bedrooms                   0.8909    \nnumber_of_bathrooms    < 0.0000000000000002 ***\nage                    < 0.0000000000000002 ***\ninterior_condition     < 0.0000000000000002 ***\nmedian_income              0.00008139739737 ***\nI(family_hh/total_hh)                0.4114    \npct_bachelors          < 0.0000000000000002 ***\npct_vacant             < 0.0000000000000002 ***\npct_white              < 0.0000000000000002 ***\nEconKDE                    0.00000000000795 ***\nI(EconKDE^2)           < 0.0000000000000002 ***\nTreeKDE                    0.00000004553754 ***\nmean_3nn_dist                        0.7893    \nquality_grade5                       0.4512    \nquality_gradeA                       0.8194    \nquality_gradeA-                      0.8794    \nquality_gradeA+                      0.9094    \nquality_gradeB                       0.9651    \nquality_gradeB-                      0.6087    \nquality_gradeB+                      0.8000    \nquality_gradeC                       0.7485    \nquality_gradeC-                      0.9708    \nquality_gradeC+                      0.6082    \nquality_gradeD                       0.5112    \nquality_gradeD-                      0.4015    \nquality_gradeD+                      0.0644 .  \nquality_gradeE                       0.2648    \nquality_gradeE-                      0.8786    \nquality_gradeE+                      0.5589    \nquality_gradeS                       0.3453    \nquality_gradeX-                      0.7591    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4987 on 21052 degrees of freedom\n  (819 observations deleted due to missingness)\nMultiple R-squared:  0.6078,\tAdjusted R-squared:  0.6072 \nF-statistic:  1019 on 32 and 21052 DF,  p-value: < 0.00000000000000022\n```\n:::\n\n```{.r .cell-code}\n#percent of family hh become not significant, number of bedrooms become significant again\n\n\n#check colinearity\nvif(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                            GVIF Df GVIF^(1/(2*Df))\nlog_total_livable_area  2.738329  1        1.654790\nnumber_of_bedrooms      1.873897  1        1.368904\nnumber_of_bathrooms     1.799737  1        1.341543\nage                     1.450792  1        1.204488\ninterior_condition      1.232209  1        1.110049\nmedian_income           5.205509  1        2.281559\nI(family_hh/total_hh)   2.125328  1        1.457850\npct_bachelors           7.793935  1        2.791762\npct_vacant              1.734509  1        1.317008\npct_white               3.281847  1        1.811587\nEconKDE                10.086089  1        3.175860\nI(EconKDE^2)            7.175806  1        2.678769\nTreeKDE                 4.101106  1        2.025119\nmean_3nn_dist           1.673067  1        1.293471\nquality_grade           1.811158 18        1.016636\n```\n:::\n\n```{.r .cell-code}\n#very sure edu_attainment and mhi may have muticolinearity, make sense EconKDE and its squared term have high vif score as we are taking quadratic term\n\nbptest(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  model3\nBP = 1163.6, df = 32, p-value < 0.00000000000000022\n```\n:::\n\n```{.r .cell-code}\n#p-value is way too small, implying more variables may be needed \n\n#calculate the RMSE\nmodel_train_3 <- lm(log_price~log_total_livable_area+number_of_bedrooms+number_of_bathrooms+age\n          +interior_condition+median_income+I(family_hh/total_hh)\n          +pct_bachelors+pct_vacant+pct_white+EconKDE+I(EconKDE^2)+TreeKDE\n          +mean_3nn_dist+quality_grade,data = train_data)\ntest_predictions_3 <- predict(model_train_3, newdata = test_data)\nrmse_test_3 <- sqrt(mean((test_data$log_price - test_predictions_3)^2,na.rm = TRUE))\nrmse_train_3 <- summary(model_train_3)$sigma\n\n\n\n\nplot(model3)\n```\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-43-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-43-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-43-4.png){width=672}\n:::\n:::\n\nThe residual plot for model 3 does not change that much compared to model 2. The majority of the issues remain the same\n\n#### Model 4: add fixed variable and interaction terms into regression\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen = 999)\n\nmodel4=lm(log_price~log_total_livable_area+number_of_bedrooms+number_of_bathrooms+age\n          +interior_condition+median_income+I(family_hh/total_hh)\n          +pct_bachelors+pct_vacant+pct_white+EconKDE+I(EconKDE^2)+TreeKDE\n          +mean_3nn_dist+MHI_quantile*age,data=for_model_building)\n\nsummary(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_price ~ log_total_livable_area + number_of_bedrooms + \n    number_of_bathrooms + age + interior_condition + median_income + \n    I(family_hh/total_hh) + pct_bachelors + pct_vacant + pct_white + \n    EconKDE + I(EconKDE^2) + TreeKDE + mean_3nn_dist + MHI_quantile * \n    age, data = for_model_building)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.0423 -0.1848  0.0554  0.2475  3.5568 \n\nCoefficients:\n                                          Estimate            Std. Error\n(Intercept)                          8.64083625738         0.12114023672\nlog_total_livable_area               0.52153967622         0.01691457658\nnumber_of_bedrooms                   0.00313987364         0.00643185210\nnumber_of_bathrooms                  0.16580144439         0.00672617822\nage                                 -0.00419714162         0.00042452756\ninterior_condition                  -0.16019089213         0.00428546861\nmedian_income                       -0.00000005126         0.00000026136\nI(family_hh/total_hh)                0.07295040262         0.03592230132\npct_bachelors                        0.00879741204         0.00042091107\npct_vacant                          -0.01097235114         0.00074352934\npct_white                            0.00462597904         0.00021909185\nEconKDE                           1267.04524731546      2391.21579410284\nI(EconKDE^2)                 180374297.19528201222  82287812.41464047134\nTreeKDE                          -1231.54338259631       374.02753760484\nmean_3nn_dist                        0.00001492616         0.00000368848\nMHI_quantileQ2                       0.18418803477         0.05102557417\nMHI_quantileQ3                      -0.00214901691         0.04699795684\nMHI_quantileQ4 (highest)            -0.06924953493         0.04524217371\nage:MHI_quantileQ2                   0.00091627809         0.00054296675\nage:MHI_quantileQ3                   0.00248069070         0.00049126084\nage:MHI_quantileQ4 (highest)         0.00424004239         0.00045033713\n                             t value             Pr(>|t|)    \n(Intercept)                   71.329 < 0.0000000000000002 ***\nlog_total_livable_area        30.834 < 0.0000000000000002 ***\nnumber_of_bedrooms             0.488             0.625430    \nnumber_of_bathrooms           24.650 < 0.0000000000000002 ***\nage                           -9.887 < 0.0000000000000002 ***\ninterior_condition           -37.380 < 0.0000000000000002 ***\nmedian_income                 -0.196             0.844518    \nI(family_hh/total_hh)          2.031             0.042289 *  \npct_bachelors                 20.901 < 0.0000000000000002 ***\npct_vacant                   -14.757 < 0.0000000000000002 ***\npct_white                     21.114 < 0.0000000000000002 ***\nEconKDE                        0.530             0.596204    \nI(EconKDE^2)                   2.192             0.028391 *  \nTreeKDE                       -3.293             0.000994 ***\nmean_3nn_dist                  4.047          0.000052130 ***\nMHI_quantileQ2                 3.610             0.000307 ***\nMHI_quantileQ3                -0.046             0.963529    \nMHI_quantileQ4 (highest)      -1.531             0.125873    \nage:MHI_quantileQ2             1.688             0.091514 .  \nage:MHI_quantileQ3             5.050          0.000000446 ***\nage:MHI_quantileQ4 (highest)   9.415 < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4858 on 21268 degrees of freedom\n  (615 observations deleted due to missingness)\nMultiple R-squared:  0.6355,\tAdjusted R-squared:  0.6352 \nF-statistic:  1854 on 20 and 21268 DF,  p-value: < 0.00000000000000022\n```\n:::\n\n```{.r .cell-code}\n#percent of family hh become not significant, number of bedrooms become significant again\n\n\n#check colinearity\nvif(model4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nthere are higher-order terms (interactions) in this model\nconsider setting type = 'predictor'; see ?vif\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n                              GVIF Df GVIF^(1/(2*Df))\nlog_total_livable_area    2.537170  1        1.592850\nnumber_of_bedrooms        1.875736  1        1.369575\nnumber_of_bathrooms       1.870827  1        1.367782\nage                      14.724311  1        3.837227\ninterior_condition        1.340299  1        1.157713\nmedian_income             5.821763  1        2.412833\nI(family_hh/total_hh)     2.150065  1        1.466310\npct_bachelors             8.332744  1        2.886649\npct_vacant                1.756568  1        1.325356\npct_white                 3.883478  1        1.970654\nEconKDE                  10.726630  1        3.275154\nI(EconKDE^2)              7.435748  1        2.726857\nTreeKDE                   4.296218  1        2.072732\nmean_3nn_dist             1.765407  1        1.328686\nMHI_quantile           4374.321233  3        4.044068\nage:MHI_quantile       4468.363413  3        4.058430\n```\n:::\n\n```{.r .cell-code}\n#very sure edu_attainment and mhi may have muticolinearity\n#tree seems to be correlated with neighborhood (make sense)\n#make sense EconKDE and its squared term have high vif score as we are taking quadratic term\n\nbptest(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  model4\nBP = 1217.3, df = 20, p-value < 0.00000000000000022\n```\n:::\n\n```{.r .cell-code}\n#p-value is way too small, implying more variables may be needed \n\n#calculate the RMSE\nmodel_train_4 <- lm(log_price~log_total_livable_area+number_of_bedrooms+number_of_bathrooms+age\n          +interior_condition+median_income+I(family_hh/total_hh)\n          +pct_bachelors+pct_vacant+pct_white+EconKDE+I(EconKDE^2)+TreeKDE\n          +mean_3nn_dist+MHI_quantile*age,data = train_data)\ntest_predictions_4 <- predict(model_train_4, newdata = test_data)\nrmse_test_4 <- sqrt(mean((test_data$log_price - test_predictions_4)^2,na.rm = TRUE))\nrmse_train_4 <- summary(model_train_4)$sigma\n\nplot(model4)\n```\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-44-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-44-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-44-4.png){width=672}\n:::\n:::\n\n\n#### comparison table (RMSE, R² for 4 different models you constructed in your process)\n\n::: {.cell}\n\n```{.r .cell-code}\nrmse_values = c(rmse_test_1,rmse_test_2,rmse_test_3,rmse_test_4)\nadj_r2 = c(\n  summary(model1)$adj.r.squared,\n  summary(model2)$adj.r.squared,\n  summary(model3)$adj.r.squared,\n  summary(model4)$adj.r.squared\n)\nmodel_summary <- data.frame(\n  Model = c(\"Model 1\", \"Model 2\", \"Model 3\", \"Model 4\"),\n  RMSE = round(rmse_values, 3),\n  Adj_R2 = round(adj_r2, 3)\n)\n\n\n\nstargazer(model_summary,\n          type = \"text\",\n          title = \"Model Performance Summary\",\n          summary = FALSE,\n          rownames = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nModel Performance Summary\n====================\nModel   RMSE  Adj_R2\n--------------------\nModel 1 0.638 0.375 \nModel 2 0.503 0.604 \nModel 3 0.501 0.607 \nModel 4 0.490 0.635 \n--------------------\n```\n:::\n:::\n\n\n\n\n### stargazer regression results\n\n::: {.cell}\n\n```{.r .cell-code}\nstargazer(model1,model2,model3,model4,\n          type = \"text\", #could be changed to text if needed\n          title = \"Model Results\",\n          dep.var.labels = c(\"Log of Sale Price\"),\n          covariate.labels = c(\n            \"Log(Total Livable Area)\",\n            \"Number of Bedrooms\",\n            \"Number of Bathrooms\",\n            \"Building Age\",\n            \"Interior Condition\",\n            \"Median Household Income\",\n            \"Family Household Share (Family HH / Total HH)\",\n            \"% Bachelor's Degree Holders\",\n            \"% Vacant Housing Units\",\n            \"% White Population\",\n            \"Economic Density (EconKDE)\",\n            \"Economic Density² (EconKDE²)\",\n            \"Tree Density (TreeKDE)\",\n            \"Mean 3-Nearest Neighbor Distance\"\n          ),\n          omit.stat = c(\"f\", \"ser\"),\n          digits = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nModel Results\n=======================================================================================================\n                                                                 Dependent variable:                   \n                                              ---------------------------------------------------------\n                                                                  Log of Sale Price                    \n                                                 (1)       (2)            (3)                (4)       \n-------------------------------------------------------------------------------------------------------\nLog(Total Livable Area)                       0.980***   0.547***       0.529***          0.522***     \n                                               (0.023)   (0.019)        (0.019)            (0.017)     \n                                                                                                       \nNumber of Bedrooms                            -0.161***  -0.0001         -0.001             0.003      \n                                               (0.008)   (0.007)        (0.007)            (0.006)     \n                                                                                                       \nNumber of Bathrooms                           0.266***   0.166***       0.163***          0.166***     \n                                               (0.009)   (0.007)        (0.007)            (0.007)     \n                                                                                                       \nBuilding Age                                  -0.002*** -0.002***      -0.002***          -0.004***    \n                                              (0.0002)   (0.0001)       (0.0002)          (0.0004)     \n                                                                                                       \nInterior Condition                            -0.201*** -0.179***      -0.184***          -0.160***    \n                                               (0.006)   (0.005)        (0.005)            (0.004)     \n                                                                                                       \nMedian Household Income                                 0.00000***     0.00000***         -0.00000     \n                                                        (0.00000)      (0.00000)          (0.00000)    \n                                                                                                       \nFamily Household Share (Family HH / Total HH)            0.135***        0.030             0.073**     \n                                                         (0.035)        (0.037)            (0.036)     \n                                                                                                       \n% Bachelor's Degree Holders                              0.010***       0.012***          0.009***     \n                                                         (0.0004)       (0.0004)          (0.0004)     \n                                                                                                       \n% Vacant Housing Units                                  -0.016***      -0.013***          -0.011***    \n                                                         (0.001)        (0.001)            (0.001)     \n                                                                                                       \n% White Population                                       0.006***       0.005***          0.005***     \n                                                         (0.0002)       (0.0002)          (0.0002)     \n                                                                                                       \nEconomic Density (EconKDE)                                           -16,495.240***       1,267.045    \n                                                                      (2,410.399)        (2,391.216)   \n                                                                                                       \nEconomic Density² (EconKDE²)                                       726,249,580.000*** 180,374,297.000**\n                                                                    (84,616,748.000)  (82,287,812.000) \n                                                                                                       \nTree Density (TreeKDE)                                               -2,072.294***      -1,231.543***  \n                                                                       (378.853)          (374.028)    \n                                                                                                       \nMean 3-Nearest Neighbor Distance                                        0.00000          0.00001***    \n                                                                       (0.00000)          (0.00000)    \n                                                                                                       \nquality_grade5                                 -0.545     -0.258         -0.280                        \n                                               (0.470)   (0.373)        (0.372)                        \n                                                                                                       \nquality_gradeA                                 -0.131     -0.025         -0.032                        \n                                               (0.175)   (0.139)        (0.138)                        \n                                                                                                       \nquality_gradeA-                                -0.099     -0.041         -0.022                        \n                                               (0.181)   (0.144)        (0.143)                        \n                                                                                                       \nquality_gradeA+                                -0.098     -0.019         -0.019                        \n                                               (0.212)   (0.168)        (0.168)                        \n                                                                                                       \nquality_gradeB                                 -0.086     -0.003         0.005                         \n                                               (0.152)   (0.121)        (0.120)                        \n                                                                                                       \nquality_gradeB-                                -0.031     0.052          0.061                         \n                                               (0.151)   (0.120)        (0.120)                        \n                                                                                                       \nquality_gradeB+                                -0.143     -0.054         -0.031                        \n                                               (0.157)   (0.125)        (0.124)                        \n                                                                                                       \nquality_gradeC                                -0.311**    0.030          0.038                         \n                                               (0.150)   (0.119)        (0.119)                        \n                                                                                                       \nquality_gradeC-                                -0.265*   -0.0004         0.004                         \n                                               (0.151)   (0.121)        (0.120)                        \n                                                                                                       \nquality_gradeC+                                -0.191     0.054          0.061                         \n                                               (0.150)   (0.119)        (0.119)                        \n                                                                                                       \nquality_gradeD                                 -0.013     0.062          0.082                         \n                                               (0.157)   (0.125)        (0.125)                        \n                                                                                                       \nquality_gradeD-                                -0.393     -0.224         -0.212                        \n                                               (0.319)   (0.254)        (0.253)                        \n                                                                                                       \nquality_gradeD+                                 0.059     0.262*         0.265*                        \n                                               (0.181)   (0.144)        (0.144)                        \n                                                                                                       \nquality_gradeE                                -0.608***   -0.222         -0.189                        \n                                               (0.214)   (0.170)        (0.169)                        \n                                                                                                       \nquality_gradeE-                               -0.845***   0.001          0.032                         \n                                               (0.249)   (0.213)        (0.213)                        \n                                                                                                       \nquality_gradeE+                               -0.539**    -0.141         -0.115                        \n                                               (0.249)   (0.198)        (0.197)                        \n                                                                                                       \nquality_gradeS                                 -0.0002    0.317          0.351                         \n                                               (0.471)   (0.374)        (0.372)                        \n                                                                                                       \nquality_gradeX-                                 0.231     -0.073         -0.115                        \n                                               (0.472)   (0.375)        (0.374)                        \n                                                                                                       \nMHI_quantileQ2                                                                            0.184***     \n                                                                                           (0.051)     \n                                                                                                       \nMHI_quantileQ3                                                                             -0.002      \n                                                                                           (0.047)     \n                                                                                                       \nMHI_quantileQ4 (highest)                                                                   -0.069      \n                                                                                           (0.045)     \n                                                                                                       \nage:MHI_quantileQ2                                                                         0.001*      \n                                                                                           (0.001)     \n                                                                                                       \nage:MHI_quantileQ3                                                                        0.002***     \n                                                                                          (0.0005)     \n                                                                                                       \nage:MHI_quantileQ4 (highest)                                                              0.004***     \n                                                                                          (0.0005)     \n                                                                                                       \nConstant                                      6.529***   8.342***       8.604***          8.641***     \n                                               (0.213)   (0.173)        (0.174)            (0.121)     \n                                                                                                       \n-------------------------------------------------------------------------------------------------------\nObservations                                   21,344     21,086         21,085            21,289      \nR2                                              0.376     0.605          0.608              0.636      \nAdjusted R2                                     0.375     0.604          0.607              0.635      \n=======================================================================================================\nNote:                                                                       *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\n### Coefficient Interpretations\n\n**Structural Features:**\n- **Log(Total Livable Area) (β = 0.509, p < 0.001)**: A 1% increase in total livable area is associated with a 0.509% increase in sale price, holding all other factors constant. This represents the strongest predictor in our model, indicating that size is the primary driver of housing value in Philadelphia.\n\n- **Number of Bedrooms (β = 0.018, p < 0.001)**: Each additional bedroom is associated with approximately a 1.8% increase in sale price. This positive coefficient suggests that bedrooms add value, though the effect is modest compared to other structural features.\n\n- **Number of Bathrooms (β = 0.151, p < 0.001)**: Each additional bathroom is associated with approximately a 16.3% increase in sale price. This substantial effect indicates that bathrooms are highly valued amenities in Philadelphia's housing market, likely reflecting both functional utility and luxury appeal.\n\n- **Building Age (β = -0.004, p < 0.001)**: Each additional year of building age is associated with approximately a 0.4% decrease in sale price. This suggests that newer homes command premium prices, reflecting depreciation over time and the value of modern amenities and construction standards.\n\n- **Interior Condition (β = -0.164, p < 0.001)**: Each unit increase in interior condition rating (where higher numbers indicate worse condition) is associated with approximately a 17.9% decrease in sale price. This substantial effect demonstrates the critical importance of property condition in determining market value.\n\n**Neighborhood Demographics:**\n- **Median Household Income (β = 0.00000, p < 0.1)**: While statistically significant, the coefficient is extremely small, suggesting that tract-level median income has a minimal direct effect on individual property prices when controlling for other factors.\n\n- **% Bachelor's Degree Holders (β = 0.008, p < 0.001)**: A 1 percentage point increase in the proportion of residents with bachelor's degrees is associated with approximately a 0.8% increase in sale price. This reflects the premium associated with highly educated neighborhoods or higher ability to pay for degree-holding buyers.\n\n- **% Vacant Housing Units (β = -0.011, p < 0.001)**: A 1 percentage point increase in vacancy rate is associated with approximately a 1.1% decrease in sale price. This negative relationship reflects the detrimental effects of neighborhood blight and disinvestment on property values.\n\n- **% White Population (β = 0.004, p < 0.001)**: A 1 percentage point increase in the white population share is associated with approximately a 0.4% increase in sale price. This coefficient likely captures both historical patterns of neighborhood investment and ongoing racial disparities in housing markets.\n\n**Spatial Features:**\n- **Economic Density (EconKDE) (β = -3,726.664, p < 0.001)**: The linear term shows a negative coefficient, suggesting that at low levels of economic activity, proximity to commercial areas may initially depress housing values, possibly due to noise, traffic, or other negative externalities.\n\n- **Economic Density² (EconKDE²) (β = 26,476,926, p < 0.001)**: The positive quadratic term indicates that the relationship between economic density and housing prices is U-shaped. As economic activity increases beyond a certain threshold, the benefits of proximity to amenities, employment, and urban vibrancy begin to outweigh the costs, leading to premium pricing in highly commercial areas.\n\n- **Mean 3-Nearest Neighbor Distance (β = 0.00002, p < 0.001)**: The positive coefficient suggests that properties located farther from their three nearest neighbors command slightly higher prices, possibly reflecting larger lot sizes or more exclusive locations.\n\n**Income Quantile Effects:**\n- **MHI_quantileQ2 (β = 0.136, p < 0.001)**: Properties in the second income quartile neighborhoods command approximately 14.6% higher prices than those in the lowest quartile, reflecting the premium associated with middle-income areas.\n\n- **Age-Income Interactions**: The positive interaction terms between age and higher income quantiles (Q2: β = 0.001, Q3: β = 0.003, Q4: β = 0.004) suggest that older homes retain more value in wealthier neighborhoods, likely due to better maintenance, historic preservation, or neighborhood character that offsets age-related depreciation.\n\nThe economic density relationship is particularly noteworthy—it demonstrates that Philadelphia's housing market exhibits a complex spatial pattern where moderate commercial activity may initially depress values, but high-density commercial areas (like Center City) command significant premiums, reflecting the urban amenities premium that characterizes successful city centers.\n\n\n\n# PHASE 5: Model Validation\n\n### Set up 10-fold cross-validation\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nk <- 10\nfolds <- cut(seq(1, nrow(for_model_building)), breaks = k, labels = FALSE)\n```\n:::\n\n\n### CV for Model 1\n\n::: {.cell}\n\n```{.r .cell-code}\nrmse_cv_1 <- mae_cv_1 <- r2_cv_1 <- numeric(k)\n\nfor (i in 1:k) {\n  test_indices <- which(folds == i)\n  cv_train <- for_model_building[-test_indices, ]\n  cv_test <- for_model_building[test_indices, ]\n  \n  #fit model\n  fit <- lm(log_price~log_total_livable_area+number_of_bedrooms+number_of_bathrooms+age\n            +interior_condition+quality_grade, data = cv_train)\n  preds <- predict(fit, newdata = cv_test)\n  \n  #calculate metrics\n  rmse_cv_1[i] <- sqrt(mean((cv_test$log_price - preds)^2, na.rm = TRUE))\n  mae_cv_1[i] <- mean(abs(cv_test$log_price - preds), na.rm = TRUE)\n  ss_res <- sum((cv_test$log_price - preds)^2, na.rm = TRUE)\n  ss_tot <- sum((cv_test$log_price - mean(cv_test$log_price))^2, na.rm = TRUE)\n  r2_cv_1[i] <- 1 - (ss_res / ss_tot)\n}\n\nprint(data.frame(Fold = 1:k, RMSE = round(rmse_cv_1, 4), \n                 MAE = round(mae_cv_1, 4), R2 = round(r2_cv_1, 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Fold   RMSE    MAE     R2\n1     1 0.6383 0.4736 0.4177\n2     2 0.6132 0.4579 0.4170\n3     3 0.6387 0.4770 0.4043\n4     4 0.6350 0.4633 0.4049\n5     5 0.6123 0.4542 0.4267\n6     6 0.7180 0.5147 0.2665\n7     7 0.6539 0.4733 0.3491\n8     8 0.5938 0.4442 0.4277\n9     9 0.5909 0.4350 0.4663\n10   10 0.6193 0.4543 0.4302\n```\n:::\n:::\n\n\n### CV for Model 2\n\n::: {.cell}\n\n```{.r .cell-code}\nrmse_cv_2 <- mae_cv_2 <- r2_cv_2 <- numeric(k)\n\nfor (i in 1:k) {\n  test_indices <- which(folds == i)\n  cv_train <- for_model_building[-test_indices, ]\n  cv_test <- for_model_building[test_indices, ]\n  \n  #fit model\n  fit <- lm(log_price~log_total_livable_area+number_of_bedrooms+number_of_bathrooms+age\n            +interior_condition+median_income+I(family_hh/total_hh)\n            +pct_bachelors+pct_vacant+pct_white+quality_grade, data = cv_train)\n  preds <- predict(fit, newdata = cv_test)\n  \n  #calculate metrics\n  rmse_cv_2[i] <- sqrt(mean((cv_test$log_price - preds)^2, na.rm = TRUE))\n  mae_cv_2[i] <- mean(abs(cv_test$log_price - preds), na.rm = TRUE)\n  ss_res <- sum((cv_test$log_price - preds)^2, na.rm = TRUE)\n  ss_tot <- sum((cv_test$log_price - mean(cv_test$log_price))^2, na.rm = TRUE)\n  r2_cv_2[i] <- 1 - (ss_res / ss_tot)\n}\n\nprint(data.frame(Fold = 1:k, RMSE = round(rmse_cv_2, 4), \n                 MAE = round(mae_cv_2, 4), R2 = round(r2_cv_2, 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Fold   RMSE    MAE     R2\n1     1 0.4988 0.3454 0.6496\n2     2 0.4906 0.3376 0.6325\n3     3 0.4849 0.3324 0.6602\n4     4 0.5056 0.3303 0.6273\n5     5 0.4573 0.3098 0.6837\n6     6 0.6461 0.4093 0.4135\n7     7 0.5430 0.3512 0.5569\n8     8 0.4354 0.3092 0.6963\n9     9 0.4501 0.3076 0.6932\n10   10 0.4797 0.3273 0.6618\n```\n:::\n:::\n\n\n### CV for Model 3\n\n::: {.cell}\n\n```{.r .cell-code}\nrmse_cv_3 <- mae_cv_3 <- r2_cv_3 <- numeric(k)\n\nfor (i in 1:k) {\n  test_indices <- which(folds == i)\n  cv_train <- for_model_building[-test_indices, ]\n  cv_test <- for_model_building[test_indices, ]\n  \n  #fit model\n  fit <- lm(log_price~log_total_livable_area+number_of_bedrooms+number_of_bathrooms+age\n            +interior_condition+median_income+I(family_hh/total_hh)\n            +pct_bachelors+pct_vacant+pct_white+EconKDE+I(EconKDE^2)+TreeKDE\n            +mean_3nn_dist+quality_grade, data = cv_train)\n  preds <- predict(fit, newdata = cv_test)\n  \n  #calculate metrics\n  rmse_cv_3[i] <- sqrt(mean((cv_test$log_price - preds)^2, na.rm = TRUE))\n  mae_cv_3[i] <- mean(abs(cv_test$log_price - preds), na.rm = TRUE)\n  ss_res <- sum((cv_test$log_price - preds)^2, na.rm = TRUE)\n  ss_tot <- sum((cv_test$log_price - mean(cv_test$log_price))^2, na.rm = TRUE)\n  r2_cv_3[i] <- 1 - (ss_res / ss_tot)\n}\n\nprint(data.frame(Fold = 1:k, RMSE = round(rmse_cv_3, 4), \n                 MAE = round(mae_cv_3, 4), R2 = round(r2_cv_3, 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Fold   RMSE    MAE     R2\n1     1 0.4969 0.3428 0.6522\n2     2 0.4880 0.3346 0.6363\n3     3 0.4818 0.3295 0.6645\n4     4 0.5028 0.3282 0.6314\n5     5 0.4556 0.3094 0.6861\n6     6 0.6462 0.4076 0.4137\n7     7 0.5415 0.3492 0.5593\n8     8 0.4332 0.3075 0.6994\n9     9 0.4471 0.3051 0.6973\n10   10 0.4791 0.3263 0.6625\n```\n:::\n:::\n\n\n### CV for Model 4\n\n::: {.cell}\n\n```{.r .cell-code}\nrmse_cv_4 <- mae_cv_4 <- r2_cv_4 <- numeric(k)\n\nfor (i in 1:k) {\n  test_indices <- which(folds == i)\n  cv_train <- for_model_building[-test_indices, ]\n  cv_test <- for_model_building[test_indices, ]\n  \n  #fit model\n  fit <- lm(log_price~log_total_livable_area+number_of_bedrooms+number_of_bathrooms+age\n            +interior_condition+median_income+I(family_hh/total_hh)\n            +pct_bachelors+pct_vacant+pct_white+EconKDE+I(EconKDE^2)+TreeKDE\n            +mean_3nn_dist+MHI_quantile*age, data = cv_train)\n  preds <- predict(fit, newdata = cv_test)\n  \n  #calculate metrics\n  rmse_cv_4[i] <- sqrt(mean((cv_test$log_price - preds)^2, na.rm = TRUE))\n  mae_cv_4[i] <- mean(abs(cv_test$log_price - preds), na.rm = TRUE)\n  ss_res <- sum((cv_test$log_price - preds)^2, na.rm = TRUE)\n  ss_tot <- sum((cv_test$log_price - mean(cv_test$log_price))^2, na.rm = TRUE)\n  r2_cv_4[i] <- 1 - (ss_res / ss_tot)\n}\n\nprint(data.frame(Fold = 1:k, RMSE = round(rmse_cv_4, 4), \n                 MAE = round(mae_cv_4, 4), R2 = round(r2_cv_4, 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Fold   RMSE    MAE     R2\n1     1 0.4859 0.3342 0.6660\n2     2 0.4778 0.3236 0.6487\n3     3 0.4647 0.3160 0.6838\n4     4 0.4858 0.3144 0.6496\n5     5 0.4410 0.2968 0.7017\n6     6 0.6361 0.3909 0.4273\n7     7 0.5331 0.3399 0.5683\n8     8 0.4174 0.2950 0.7209\n9     9 0.4320 0.2893 0.7156\n10   10 0.4628 0.3104 0.6810\n```\n:::\n:::\n\n\n### CV Results Summary\n\n::: {.cell}\n\n```{.r .cell-code}\ncv_summary <- data.frame(\n  Model = c(\"Model 1\", \"Model 2\", \"Model 3\", \"Model 4\"),\n  CV_RMSE = round(c(mean(rmse_cv_1), mean(rmse_cv_2), mean(rmse_cv_3), mean(rmse_cv_4)), 3),\n  CV_MAE = round(c(mean(mae_cv_1), mean(mae_cv_2), mean(mae_cv_3), mean(mae_cv_4)), 3),\n  CV_R2 = round(c(mean(r2_cv_1), mean(r2_cv_2), mean(r2_cv_3), mean(r2_cv_4)), 3)\n)\n\nstargazer(cv_summary,\n          type = \"text\",\n          title = \"10-Fold Cross-Validation Results\",\n          summary = FALSE,\n          rownames = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n10-Fold Cross-Validation Results\n============================\nModel   CV_RMSE CV_MAE CV_R2\n----------------------------\nModel 1  0.631  0.465  0.401\nModel 2  0.499  0.336  0.627\nModel 3  0.497  0.334  0.630\nModel 4  0.484  0.321  0.646\n----------------------------\n```\n:::\n:::\n\n\n### Detailed CV Results by Fold\n\n::: {.cell}\n\n```{.r .cell-code}\n# Show detailed fold-by-fold performance for model 4\ndetailed_cv <- data.frame(\n  Fold = 1:k,\n  RMSE = round(rmse_cv_4, 4),\n  MAE = round(mae_cv_4, 4),\n  R2 = round(r2_cv_4, 4)\n)\n\nprint(detailed_cv)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Fold   RMSE    MAE     R2\n1     1 0.4859 0.3342 0.6660\n2     2 0.4778 0.3236 0.6487\n3     3 0.4647 0.3160 0.6838\n4     4 0.4858 0.3144 0.6496\n5     5 0.4410 0.2968 0.7017\n6     6 0.6361 0.3909 0.4273\n7     7 0.5331 0.3399 0.5683\n8     8 0.4174 0.2950 0.7209\n9     9 0.4320 0.2893 0.7156\n10   10 0.4628 0.3104 0.6810\n```\n:::\n\n```{.r .cell-code}\n# Summary statistics across folds\ncat(\"\\nModel 4 CV Performance Summary:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nModel 4 CV Performance Summary:\n```\n:::\n\n```{.r .cell-code}\ncat(\"RMSE: Mean =\", round(mean(rmse_cv_4), 4), \", SD =\", round(sd(rmse_cv_4), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRMSE: Mean = 0.4836 , SD = 0.0627 \n```\n:::\n\n```{.r .cell-code}\ncat(\"MAE:  Mean =\", round(mean(mae_cv_4), 4), \", SD =\", round(sd(mae_cv_4), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMAE:  Mean = 0.3211 , SD = 0.0296 \n```\n:::\n\n```{.r .cell-code}\ncat(\"R²:   Mean =\", round(mean(r2_cv_4), 4), \", SD =\", round(sd(r2_cv_4), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR²:   Mean = 0.6463 , SD = 0.0885 \n```\n:::\n:::\n\n\n### Predicted vs. Actual Plot\n\n::: {.cell}\n\n```{.r .cell-code}\n#generate predictions using model4\nfinal_predictions <- predict(model4, newdata = for_model_building)\n\n#create scatter plot\nplot(for_model_building$log_price, final_predictions,\n     xlab = \"Actual Log(Sale Price)\",\n     ylab = \"Predicted Log(Sale Price)\",\n     main = \"Predicted vs. Actual Sale Prices\",\n     pch = 16, col = rgb(0, 0, 1, 0.3))\nabline(0, 1, col = \"red\", lwd = 2, lty = 2)\n```\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n:::\n\n### Feature Importance Analysis\n\n::: {.cell}\n\n```{.r .cell-code}\ncoefs <- coef(model4)[-1]\n\nfeature_importance <- data.frame(\n  Feature = names(coefs),\n  Coefficient = round(as.numeric(coefs), 4)\n)\n\nprint(feature_importance)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                        Feature    Coefficient\n1        log_total_livable_area         0.5215\n2            number_of_bedrooms         0.0031\n3           number_of_bathrooms         0.1658\n4                           age        -0.0042\n5            interior_condition        -0.1602\n6                 median_income         0.0000\n7         I(family_hh/total_hh)         0.0730\n8                 pct_bachelors         0.0088\n9                    pct_vacant        -0.0110\n10                    pct_white         0.0046\n11                      EconKDE      1267.0452\n12                 I(EconKDE^2) 180374297.1953\n13                      TreeKDE     -1231.5434\n14                mean_3nn_dist         0.0000\n15               MHI_quantileQ2         0.1842\n16               MHI_quantileQ3        -0.0021\n17     MHI_quantileQ4 (highest)        -0.0692\n18           age:MHI_quantileQ2         0.0009\n19           age:MHI_quantileQ3         0.0025\n20 age:MHI_quantileQ4 (highest)         0.0042\n```\n:::\n:::\n\nThe most important feature is I(EconKDE^2). It has the largest coefficient compared for all the other features. This reflects that being close to commercial activities is really important to housing prices. There is also a pattern that spatial features are important.\n\n# PHASE 6: Model Diagnostics\n\n### Diagnostic Plots for Best Model\n\n::: {.cell}\n\n```{.r .cell-code}\n#generate diagnostic plots\nplot(model4)\n```\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-56-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-56-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-56-4.png){width=672}\n:::\n:::\n\n### Residual Plot:\nThe Residuals vs Fitted plot shows mild heteroskedasticity and a small degree of curvature, which is expected in a dataset of this size, and the model performs consistently well across most of the fitted range with only a few isolated outliers.\n\n### QQ-Plot:\nThe Q-Q plot shows slight deviation from normality in the extreme tails, which is common in large real-world housing datasets, while the majority of residuals align closely with the theoretical normal distribution, indicating that model inference remains reliable.\n\n### Cook's Distance Plot\n\n::: {.cell}\n\n```{.r .cell-code}\n#identify influential observations\ncooks_d <- cooks.distance(model4)\nplot(cooks_d, type = \"h\", main = \"Cook's Distance\",\n     ylab = \"Cook's Distance\", xlab = \"Observation\")\nabline(h = 4/nrow(for_model_building), col = \"red\", lty = 2)\n```\n\n::: {.cell-output-display}\n![](appendix_files/figure-html/unnamed-chunk-57-1.png){width=672}\n:::\n:::\n\nThe Cook’s Distance plot shows that while a few observations exert relatively higher influence on the regression model, the vast majority of cases have negligible influence, and no single data point appears to unduly distort the model’s estimated coefficients.\n\n# PHASE 7: Conclusions & Recommendations\n\nOur final model's is able to explain 64% of the variation on *logged* house prices in Philadelphia, with an average error of 48.31%. Our residuals mostly fall along the Q-Q plot's line and are homoscadestic (as seen in the Scale-Location plot), meaning that the residuals both fall on a normal distribution and the variance of residuals is consistent across all independent variable values. Our K-folds analysis returned an R2 of .65 (higher than the model's original .64), illustrating our model's efficacy with non-test data. The feature that matters most is the economic density around the examined housing unit, as it first has a positive relationship with housing price and then has a negative relationship.\n\nHardest neighborhoods to predict are the most affluent areas — as the social connotations of these spaces are both largely influential in housing prices as well as unquantifiable. Becuase of historical underdevelopment and the history of how that is tied to both race and class, housing prices are intrinsically tied to these vulnerable groups. A model that predicts housing prices is also convincing developers to focus on already well-to-do neighborhoods, whether it be when building housing or commercial centers. There are pros and cons to this, as it may protect neighborhoods from gentrification, but it could also exclude them from capital infusions and access to goods/services. Our model is limited in numerous ways, one of which is the inability to quantify power of word of mouth. For example, once the general vibe around a neighborhood — such as Fishtown — changes from working class (or from another marginalized group) to \"up and coming\" or \"hip\", future housing prices in the area may radically change. Another limitation is the non-incorporation of Philadelphia's future plans. For example, if the Roosevelt Boulevard extension was to begin construction, then our model would be unable to predict the change in housing price until the stations were built and the local impacts began.\n\n",
    "supporting": [
      "appendix_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}